<?php

declare(strict_types=1);

return [
    ep('EP-AD-030', 'SP-03', 'GET', '/platform/refs/governorates', 'platform', 'ad.refs.view', [
        'name' => 'List governorates',
        'name_ar' => 'المحافظات',
        'q' => listQuery(),
        'r' => [['id' => 1, 'name' => 'دمشق', 'order' => 1, 'status' => 'active', 'zones_count' => 18]],
    ]),
    ep('EP-AD-030C', 'SP-03', 'GET', '/platform/refs/governorates/{id}', 'platform', 'ad.refs.view', [
        'name' => 'Show governorate',
        'name_ar' => 'تفاصيل محافظة',
        'r' => ['id' => 1, 'name' => 'دمشق', 'order' => 1, 'status' => 'active', 'zones_count' => 18],
        'e' => [404 => 'not_found'],
    ]),
    ep('EP-AD-031', 'SP-03', 'POST', '/platform/refs/governorates', 'platform', 'ad.refs.create', [
        'name' => 'Create governorate',
        'name_ar' => 'إنشاء محافظة',
        'b' => ['name' => 'ريف دمشق', 'order' => 2],
        'r' => ['id' => 2],
    ]),
    ep('EP-AD-032', 'SP-03', 'GET', '/platform/refs/zones', 'platform', 'ad.refs.view', [
        'name' => 'List zones',
        'name_ar' => 'المناطق',
        'q' => listQuery(['filter[governorate_id]' => '1']),
        'r' => [[
            'id' => 12,
            'name' => 'المزة',
            'governorate' => ['id' => 1, 'name' => 'دمشق'],
            'district' => 'المزة',
            'polygon' => null,
            'order' => 3,
            'status' => 'active',
            'retailers_count' => 240,
            'reps_count' => 8,
            'channels_count' => 4,
        ]],
    ]),
    ep('EP-AD-032C', 'SP-03', 'GET', '/platform/refs/zones/{id}', 'platform', 'ad.refs.view', [
        'name' => 'Show zone',
        'name_ar' => 'تفاصيل منطقة',
        'r' => [
            'id' => 12,
            'name' => 'المزة',
            'governorate' => ['id' => 1, 'name' => 'دمشق'],
            'district' => 'المزة',
            'status' => 'active',
        ],
        'e' => [404 => 'not_found'],
    ]),
    ep('EP-AD-033', 'SP-03', 'POST', '/platform/refs/zones', 'platform', 'ad.refs.create', [
        'name' => 'Create zone',
        'name_ar' => 'إنشاء منطقة',
        'b' => [
            'governorate_id' => 1,
            'name' => 'كفرسوسة',
            'district' => 'كفرسوسة',
            'polygon' => null,
            'order' => 4,
        ],
        'r' => ['id' => 13],
    ]),
    ep('EP-AD-034', 'SP-03', 'PATCH', '/platform/refs/zones/{id}/status', 'platform', 'ad.refs.disable', [
        'name' => 'Change zone status',
        'name_ar' => 'تعطيل/تفعيل منطقة',
        'b' => ['status' => 'disabled', 'reason' => 'إعادة ترسيم الحدود'],
        'r' => ['affected' => ['retailers' => 12, 'reps' => 2, 'open_orders' => 3]],
        'd' => 'Impact is returned before confirmation (REQ-AD-031).',
        'crit' => true,
    ]),
    ep('EP-AD-035A', 'SP-03', 'GET', '/platform/refs/activity-types', 'platform', 'ad.refs.view', [
        'name' => 'List activity types',
        'name_ar' => 'أنواع النشاط',
        'q' => listQuery(),
        'r' => [['id' => 3, 'name' => 'بقالة', 'icon' => 'grocery', 'order' => 1]],
    ]),
    ep('EP-AD-035C', 'SP-03', 'GET', '/platform/refs/activity-types/{id}', 'platform', 'ad.refs.view', [
        'name' => 'Show activity type',
        'name_ar' => 'تفاصيل نوع نشاط',
        'r' => ['id' => 3, 'name' => 'بقالة', 'icon' => 'grocery', 'order' => 1],
        'e' => [404 => 'not_found'],
    ]),
    ep('EP-AD-035B', 'SP-03', 'POST', '/platform/refs/activity-types', 'platform', 'ad.refs.create', [
        'name' => 'Create activity type',
        'name_ar' => 'إنشاء نوع نشاط',
        'b' => [
            'name' => 'سوبر ماركت',
            'icon' => 'supermarket',
            'description' => 'محلات تجزئة كبيرة',
            'suggested_category_ids' => [10, 11],
            'order' => 2,
        ],
        'r' => ['id' => 4],
    ]),
    ep('EP-AD-036A', 'SP-03', 'GET', '/platform/refs/root-categories', 'platform', 'ad.refs.view', [
        'name' => 'List root categories',
        'name_ar' => 'الفئات الجذر',
        'q' => listQuery(),
        'r' => [['id' => 10, 'name' => 'مواد غذائية', 'icon' => 'food', 'order' => 1]],
    ]),
    ep('EP-AD-036C', 'SP-03', 'GET', '/platform/refs/root-categories/{id}', 'platform', 'ad.refs.view', [
        'name' => 'Show root category',
        'name_ar' => 'تفاصيل فئة جذر',
        'r' => ['id' => 10, 'name' => 'مواد غذائية', 'icon' => 'food', 'order' => 1],
        'e' => [404 => 'not_found'],
    ]),
    ep('EP-AD-036B', 'SP-03', 'POST', '/platform/refs/root-categories', 'platform', 'ad.refs.create', [
        'name' => 'Create root category',
        'name_ar' => 'إنشاء فئة جذر',
        'b' => [
            'name' => 'منظفات',
            'image' => null,
            'icon' => 'clean',
            'activity_type_ids' => [3, 4],
            'order' => 2,
        ],
        'r' => ['id' => 11],
    ]),
    ep('EP-AD-037A', 'SP-03', 'GET', '/platform/refs/sale-units', 'platform', 'ad.refs.view', [
        'name' => 'List sale units',
        'name_ar' => 'وحدات البيع',
        'q' => listQuery(),
        'r' => [['id' => 3, 'name' => 'قطعة', 'abbr' => 'pcs', 'default_factor' => 1]],
    ]),
    ep('EP-AD-037C', 'SP-03', 'GET', '/platform/refs/sale-units/{id}', 'platform', 'ad.refs.view', [
        'name' => 'Show sale unit',
        'name_ar' => 'تفاصيل وحدة بيع',
        'r' => ['id' => 3, 'name' => 'قطعة', 'abbr' => 'pcs', 'default_factor' => 1],
        'e' => [404 => 'not_found'],
    ]),
    ep('EP-AD-037B', 'SP-03', 'POST', '/platform/refs/sale-units', 'platform', 'ad.refs.create', [
        'name' => 'Create sale unit',
        'name_ar' => 'إنشاء وحدة بيع',
        'b' => ['name' => 'كرتون', 'abbr' => 'ctn', 'default_factor' => 12],
        'r' => ['id' => 5],
    ]),
    ep('EP-AD-038A', 'SP-03', 'GET', '/platform/refs/equipments', 'platform', 'ad.refs.view', [
        'name' => 'List equipments',
        'name_ar' => 'التجهيزات',
        'q' => listQuery(),
        'r' => [['id' => 1, 'name' => 'ثلاجة عرض', 'icon' => 'fridge']],
    ]),
    ep('EP-AD-038C', 'SP-03', 'GET', '/platform/refs/equipments/{id}', 'platform', 'ad.refs.view', [
        'name' => 'Show equipment',
        'name_ar' => 'تفاصيل تجهيز',
        'r' => ['id' => 1, 'name' => 'ثلاجة عرض', 'icon' => 'fridge'],
        'e' => [404 => 'not_found'],
    ]),
    ep('EP-AD-038B', 'SP-03', 'POST', '/platform/refs/equipments', 'platform', 'ad.refs.create', [
        'name' => 'Create equipment',
        'name_ar' => 'إنشاء تجهيز',
        'b' => ['name' => 'فريزر', 'icon' => 'freezer', 'description' => 'حفظ مجمّد'],
        'r' => ['id' => 2],
    ]),
    ep('EP-AD-039A', 'SP-03', 'GET', '/platform/refs/currencies', 'platform', 'ad.refs.currency', [
        'name' => 'List currencies',
        'name_ar' => 'العملات',
        'q' => listQuery(),
        'r' => [['id' => 1, 'iso' => 'SYP', 'name' => 'ليرة سورية', 'decimals' => 0, 'is_display_currency' => true]],
    ]),
    ep('EP-AD-039C', 'SP-03', 'GET', '/platform/refs/currencies/{id}', 'platform', 'ad.refs.currency', [
        'name' => 'Show currency',
        'name_ar' => 'تفاصيل عملة',
        'r' => ['id' => 1, 'iso' => 'SYP', 'name' => 'ليرة سورية', 'decimals' => 0, 'is_display_currency' => true],
        'e' => [404 => 'not_found'],
    ]),
    ep('EP-AD-039B', 'SP-03', 'POST', '/platform/refs/currencies', 'platform', 'ad.refs.currency', [
        'name' => 'Create currency',
        'name_ar' => 'إنشاء عملة',
        'b' => ['iso' => 'USD', 'name' => 'دولار', 'decimals' => 2, 'is_display_currency' => false],
        'r' => ['id' => 2],
    ]),
    ep('EP-AD-040', 'SP-03', 'POST', '/platform/refs/fx-rates', 'platform', 'ad.refs.currency', [
        'name' => 'Post FX rate',
        'name_ar' => 'سعر صرف',
        'b' => [
            'currency_id' => 2,
            'rate' => 1500000,
            'effective_from' => '2026-03-01T00:00:00+03:00',
            'source' => 'manual',
        ],
        'r' => ['id' => 88],
        'd' => 'Does not reprice open orders (BR-AD-19). rate is integer minor units.',
    ]),
    ep('EP-AD-041', 'SP-03', 'POST', '/platform/refs/import', 'platform', 'ad.refs.import', [
        'name' => 'Import references',
        'name_ar' => 'استيراد مرجعيات',
        'mp' => true,
        'b' => ['type' => 'zones', 'file' => null, 'dry_run' => true],
        'r' => [
            'preview' => [['row' => 2, 'name' => 'المزة']],
            'errors' => [['row' => 5, 'column' => 'governorate_id', 'message' => 'not found']],
        ],
    ]),

    ep('EP-AD-050', 'SP-04', 'GET', '/platform/channels', 'platform', 'ad.channels.view', [
        'name' => 'List supply channels',
        'name_ar' => 'قنوات التوريد',
        'q' => listQuery([
            'filter[status]' => 'active',
            'filter[plan_id]' => '2',
            'filter[governorate_id]' => '1',
            'filter[subscription_status]' => 'active',
            'filter[over_limit]' => '0',
            'filter[idle]' => '0',
        ]),
        'r' => [[
            'id' => 1,
            'name' => 'شركة النور',
            'slug' => 'al-nour',
            'status' => 'active',
            'plan' => ['id' => 2, 'key' => 'growth'],
            'governorates' => [['id' => 1, 'name' => 'دمشق']],
            'active_retailers' => 420,
            'reps' => 18,
            'orders_30d' => 3100,
            'gmv' => 1850000000,
            'subscription_status' => 'active',
            'last_activity_at' => '2026-03-01T08:40:00+03:00',
        ]],
    ]),
    ep('EP-AD-051', 'SP-04', 'POST', '/platform/channels', 'platform', 'ad.channels.create', [
        'name' => 'Create channel',
        'name_ar' => 'إنشاء قناة',
        'b' => [
            'name' => 'شركة الشام',
            'slug' => 'al-sham',
            'legal_form' => 'llc',
            'cr_number' => 'C12345',
            'documents' => [],
            'governorate_ids' => [1],
            'zone_ids' => [12, 13],
            'activity_type_ids' => [3, 4],
            'logo' => null,
            'internal_note' => 'شراكة تجريبية',
            'plan_id' => 2,
            'billing_cycle' => 'yearly',
            'trial_days' => 14,
            'limits' => [
                'users' => 25,
                'warehouses' => 2,
                'reps' => 20,
                'skus' => 5000,
                'storage_mb' => 2048,
            ],
            'custom_discount' => 0,
            'manager' => [
                'name' => 'محمد علي',
                'phone' => '+963944000000',
                'email' => 'manager@alsham.sy',
                'invite_via' => 'whatsapp',
            ],
        ],
        'r' => ['id' => 9, 'status' => 'provisioning', 'provisioning_job_id' => 'job_prov_9'],
        'd' => 'Must respond under 500ms (AC-AD-03). Provisioning is async.',
    ]),
    ep('EP-AD-052', 'SP-04', 'GET', '/platform/channels/{id}', 'platform', 'ad.channels.view', [
        'name' => 'Channel detail',
        'name_ar' => 'تفاصيل القناة',
        'r' => [
            'channel' => ['id' => 1, 'name' => 'شركة النور', 'status' => 'active'],
            'manager' => ['id' => 10, 'name' => 'محمد علي', 'phone' => '+963944000000'],
            'subscription' => ['plan' => 'growth', 'status' => 'active', 'next_renewal' => '2027-03-01'],
            'kpis' => ['gmv_30d' => 1850000000, 'orders_30d' => 3100],
            'timeline' => [['at' => '2026-01-01T00:00:00+03:00', 'event' => 'created']],
            'internal_notes' => [],
        ],
    ]),
    ep('EP-AD-053', 'SP-04', 'POST', '/platform/channels/{id}/retry-provisioning', 'platform', 'ad.channels.update', [
        'name' => 'Retry provisioning',
        'name_ar' => 'إعادة التجهيز',
        'b' => new stdClass(),
        'r' => ['job_id' => 'job_prov_9b'],
        'd' => 'Idempotent (REQ-AD-023).',
    ]),
    ep('EP-AD-054', 'SP-04', 'POST', '/platform/channels/{id}/transition', 'platform', 'ad.channels.suspend', [
        'name' => 'Transition channel status',
        'name_ar' => 'تغيير حالة القناة',
        'b' => ['to_status' => 'suspended', 'reason' => 'تأخر سداد فاتورة المنصة'],
        'r' => ['status' => 'suspended', 'allowed_next' => ['active', 'archived']],
        'e' => [409 => 'illegal_transition'],
        'd' => 'Permission is ad.channels.suspend / ad.channels.archive depending on target.',
        'crit' => true,
    ]),
    ep('EP-AD-055', 'SP-04', 'PUT', '/platform/channels/{id}/limits', 'platform', 'ad.billing.assign_plan', [
        'name' => 'Override channel limits',
        'name_ar' => 'حدود القناة',
        'b' => [
            'limits' => ['reps' => 30, 'skus' => 8000],
            'temporary_until' => '2026-04-01T00:00:00+03:00',
            'reason' => 'موسم رمضان',
        ],
        'r' => ['limits' => ['users' => 25, 'warehouses' => 2, 'reps' => 30, 'skus' => 8000, 'storage_mb' => 2048]],
    ]),
    ep('EP-AD-056', 'SP-04', 'GET', '/platform/channels/{id}/usage', 'platform', 'ad.channels.view', [
        'name' => 'Channel usage',
        'name_ar' => 'استخدام القناة',
        'q' => ['range' => '30d'],
        'r' => [
            'series' => [['day' => '2026-02-28', 'orders' => 110, 'gmv' => 62000000]],
            'limit_usage' => ['reps' => ['used' => 18, 'limit' => 20], 'skus' => ['used' => 2100, 'limit' => 5000]],
            'failed_jobs' => 2,
            'sync_status' => 'healthy',
        ],
    ]),
    ep('EP-AD-057', 'SP-04', 'POST', '/platform/channels/{id}/export', 'platform', 'ad.channels.export', [
        'name' => 'Export channel data',
        'name_ar' => 'تصدير بيانات القناة',
        'b' => ['password_confirmation' => '********'],
        'r' => ['job_id' => 'job_ch_export_1'],
        'crit' => true,
        'e' => [403 => 'requires_password_confirm'],
    ]),
    ep('EP-AD-058', 'SP-04', 'DELETE', '/platform/channels/{id}', 'platform', 'ad.channels.delete', [
        'name' => 'Delete channel',
        'name_ar' => 'حذف قناة',
        'b' => [
            'password_confirmation' => '********',
            'otp_code' => '123456',
            'typed_name' => 'شركة النور',
            'second_approver_id' => 2,
        ],
        'r' => ['deletion_request_id' => 77],
        'd' => 'Archived ≥ 30 days. Dual approval. otp_code is Identity step-up: TOTP if 2FA enabled, else phone OTP from EP-AD-005A.',
        'dual' => true,
        'crit' => true,
    ]),
];
