<?php

declare(strict_types=1);

return [
    ep('EP-AD-080', 'SP-14', 'POST', '/platform/notifications/broadcast', 'platform', 'ad.notify.broadcast', [
        'name' => 'Broadcast notification',
        'name_ar' => 'بث إشعار المنصة',
        'b' => [
            'title' => 'صيانة مجدولة',
            'body' => 'المنصة ستتوقف الساعة 02:00',
            'targeting' => ['type' => 'all_channels', 'ids' => []],
            'channels' => ['push', 'in_app'],
            'scheduled_at' => null,
        ],
        'r' => ['id' => 501, 'status' => 'pending_approval'],
        'dual' => true,
        'crit' => true,
    ]),

    ep('EP-AD-090', 'SP-16', 'GET', '/platform/dashboard', 'platform', 'ad.dashboard.view', [
        'name' => 'Platform dashboard',
        'name_ar' => 'لوحة المنصة',
        'r' => [
            'cards' => [
                'channels' => ['active' => 48, 'suspended' => 2],
                'retailers' => ['active' => 12400],
                'reps' => ['on_duty' => 310],
                'orders' => ['today' => 1860],
                'gmv' => ['today' => 420000000, 'month' => 9800000000],
                'platform_revenue' => ['month' => 185000000],
                'integrations_health' => ['whatsapp' => 'ok', 'sms' => 'degraded'],
                'sync' => ['pending_operations' => 12],
            ],
            'alerts' => [
                ['type' => 'channel_idle', 'count' => 3, 'action_url' => '/platform/channels?filter[idle]=1'],
            ],
            'charts' => ['daily_gmv' => [], 'adoption' => []],
        ],
        'd' => 'Read from daily snapshots (BR-AD-23). Nine alert types in DOC-07 §4.1.2.',
    ]),
    ep('EP-AD-091', 'SP-16', 'GET', '/platform/reports/{type}', 'platform', 'ad.reports.view', [
        'name' => 'Platform report',
        'name_ar' => 'تقرير المنصة',
        'q' => ['date_from' => '2026-02-01', 'date_to' => '2026-02-28'],
        'r' => ['type' => 'gmv', 'rows' => [], 'totals' => []],
        'd' => 'type ∈ gmv | adoption | operations | growth | quality',
    ]),
    ep('EP-AD-092', 'SP-16', 'GET', '/platform/exports/{jobId}', 'platform', 'ad.reports.view', [
        'name' => 'Export job status',
        'name_ar' => 'حالة التصدير',
        'r' => ['status' => 'ready', 'download_url' => 'https://files.example/exports/job_1?exp=24h'],
        'd' => 'download_url valid 24 hours. Rate: 5 exports/hour.',
    ]),

    ep('EP-AD-100A', 'SP-17', 'GET', '/platform/plans', 'platform', 'ad.billing.plans', [
        'name' => 'List plans',
        'name_ar' => 'الخطط',
        'q' => listQuery(),
        'r' => [[
            'id' => 2,
            'name' => 'نمو',
            'key' => 'growth',
            'price_monthly' => 25000000,
            'price_yearly' => 250000000,
            'currency_id' => 1,
            'limits' => ['users' => 25, 'warehouses' => 2, 'reps' => 20, 'skus' => 5000, 'storage_mb' => 2048, 'otp_monthly' => 20000],
            'features' => ['loyalty', 'multi_warehouse'],
            'on_exceed' => 'block',
            'trial_days' => 14,
            'is_public' => true,
        ]],
    ]),
    ep('EP-AD-100B', 'SP-17', 'POST', '/platform/plans', 'platform', 'ad.billing.plans', [
        'name' => 'Create plan',
        'name_ar' => 'إنشاء خطة',
        'b' => [
            'name' => 'مؤسسي',
            'key' => 'enterprise',
            'price_monthly' => 75000000,
            'price_yearly' => 750000000,
            'currency_id' => 1,
            'limits' => ['users' => 100, 'warehouses' => 10, 'reps' => 80, 'skus' => 20000, 'storage_mb' => 10240, 'otp_monthly' => 100000],
            'features' => ['loyalty', 'multi_warehouse', 'custom_sso'],
            'on_exceed' => 'warn',
            'trial_days' => 30,
            'is_public' => false,
        ],
        'r' => ['id' => 3],
    ]),
    ep('EP-AD-101', 'SP-17', 'GET', '/platform/subscriptions', 'platform', 'ad.billing.view', [
        'name' => 'Subscriptions',
        'name_ar' => 'الاشتراكات',
        'q' => listQuery(['filter[status]' => 'past_due']),
        'r' => [[
            'channel' => ['id' => 1, 'name' => 'شركة النور'],
            'plan' => 'growth',
            'cycle' => 'yearly',
            'next_renewal' => '2027-03-01',
            'amount' => 250000000,
            'status' => 'active',
        ]],
    ]),
    ep('EP-AD-102', 'SP-17', 'POST', '/platform/channels/{id}/plan', 'platform', 'ad.billing.assign_plan', [
        'name' => 'Assign plan',
        'name_ar' => 'تعيين خطة',
        'b' => [
            'plan_id' => 3,
            'cycle' => 'yearly',
            'effective_from' => '2026-04-01',
            'reason' => 'ترقية بعد نمو الطلبات',
        ],
        'r' => ['subscription_id' => 19, 'status' => 'scheduled'],
    ]),
    ep('EP-AD-103', 'SP-17', 'GET', '/platform/platform-invoices', 'platform', 'ad.billing.view', [
        'name' => 'Platform invoices',
        'name_ar' => 'فواتير المنصة',
        'q' => listQuery(['filter[status]' => 'open']),
        'r' => [[
            'id' => 40,
            'no' => 'PF-2026-0040',
            'channel' => ['id' => 1, 'name' => 'شركة النور'],
            'amount' => 250000000,
            'issued_at' => '2026-03-01',
            'due_at' => '2026-03-15',
            'status' => 'open',
            'pdf_url' => 'https://files.example/pf-40.pdf',
        ]],
    ]),
    ep('EP-AD-104', 'SP-17', 'POST', '/platform/platform-invoices/{id}/waive', 'platform', 'ad.billing.waive', [
        'name' => 'Waive invoice',
        'name_ar' => 'إعفاء فاتورة منصة',
        'b' => ['reason' => 'تعويض انقطاع خدمة أسبوع'],
        'r' => ['status' => 'waived'],
        'dual' => true,
        'crit' => true,
        'd' => 'Critical + dual + SOD-07.',
    ]),
    ep('EP-AD-105', 'SP-17', 'GET', '/platform/dunning', 'platform', 'ad.billing.dunning', [
        'name' => 'Dunning queue',
        'name_ar' => 'تحصيل المتأخرات',
        'q' => listQuery(),
        'r' => [[
            'channel' => ['id' => 9, 'name' => 'شركة الشام'],
            'amount' => 25000000,
            'days_late' => 12,
            'reminders_sent' => 2,
            'next_action' => 'suspend_warning',
        ]],
    ]),

    ep('EP-AD-110A', 'SP-17', 'GET', '/platform/features', 'platform', 'ad.features.view', [
        'name' => 'Feature flags',
        'name_ar' => 'مفاتيح الميزات',
        'q' => listQuery(),
        'r' => [[
            'key' => 'offline_orders',
            'description' => 'إرسال الطلب دون اتصال',
            'enabled_globally' => true,
            'rollout_percent' => 100,
            'channel_ids' => [],
            'scopes' => ['retailer'],
            'planned_removal_at' => null,
        ]],
    ]),
    ep('EP-AD-110B', 'SP-17', 'POST', '/platform/features', 'platform', 'ad.features.manage', [
        'name' => 'Create feature flag',
        'name_ar' => 'إنشاء مفتاح ميزة',
        'b' => [
            'key' => 'rep_live_tracking',
            'description' => 'تتبع المندوب الحي',
            'enabled_globally' => false,
            'rollout_percent' => 10,
            'channel_ids' => [1],
            'scopes' => ['rep', 'retailer'],
            'planned_removal_at' => null,
        ],
        'r' => ['key' => 'rep_live_tracking'],
    ]),
    ep('EP-AD-111', 'SP-17', 'POST', '/platform/features/{key}/override', 'platform', 'ad.features.override', [
        'name' => 'Override feature for channel',
        'name_ar' => 'تجاوز ميزة لقناة',
        'b' => ['channel_id' => 1, 'enabled' => true, 'reason' => 'تجربة بيتا'],
        'r' => ['key' => 'rep_live_tracking', 'channel_id' => 1, 'enabled' => true],
    ]),
    ep('EP-AD-112', 'SP-17', 'POST', '/platform/app-versions', 'platform', 'ad.content.publish_version', [
        'name' => 'Publish app version',
        'name_ar' => 'نشر نسخة تطبيق',
        'b' => [
            'app' => 'retailer',
            'platform' => 'android',
            'version' => '1.4.3',
            'build' => 143,
            'min_supported' => '1.3.0',
            'release_notes' => 'تحسين المزامنة',
            'rollout' => 25,
            'store_url' => 'https://play.google.com/store/apps/details?id=sy.b2b.retailer',
        ],
        'r' => ['id' => 14],
    ]),
    ep('EP-AD-113', 'SP-17', 'POST', '/platform/app-versions/{id}/force-update', 'platform', 'ad.content.force_update', [
        'name' => 'Force update',
        'name_ar' => 'فرض التحديث',
        'b' => ['reason' => 'كسر توافق API في مسار السلة'],
        'r' => ['force_update' => true],
        'dual' => true,
        'crit' => true,
        'd' => 'Only for a real API breaking change (BR-AD-17).',
    ]),

    ep('EP-AD-120', 'SP-17', 'GET', '/platform/support/search', 'platform', 'ad.support.search', [
        'name' => 'Support search',
        'name_ar' => 'بحث الدعم',
        'q' => ['q' => '+963933000000'],
        'r' => [
            'retailers' => [['id' => 481, 'shop_name' => 'بقالية النور', 'channel_badge' => 'النور']],
            'reps' => [],
            'orders' => [],
            'invoices' => [],
            'receipts' => [],
        ],
        'd' => 'q: phone, name, shop, order no, invoice no, receipt no.',
    ]),
    ep('EP-AD-121', 'SP-17', 'GET', '/platform/support/users/{type}/{id}', 'platform', 'ad.support.view_profile', [
        'name' => '360 user card',
        'name_ar' => 'بطاقة المستخدم 360',
        'r' => [
            'profile' => ['id' => 481, 'type' => 'retailer', 'shop_name' => 'بقالية النور'],
            'sections' => ['identity', 'channel', 'orders', 'finance', 'devices', 'audit', 'tickets'],
        ],
    ]),
    ep('EP-AD-122', 'SP-17', 'POST', '/platform/support/impersonate', 'platform', 'ad.support.impersonate', [
        'name' => 'Impersonate',
        'name_ar' => 'انتحال جلسة دعم',
        'b' => [
            'user_type' => 'retailer',
            'user_id' => 481,
            'reason' => 'تشخيص سلة لا تُرسل — تذكرة SUP-512',
            'write_enabled' => false,
            'password_confirmation' => '********',
            'otp_code' => '123456',
        ],
        'r' => ['impersonation_token' => 'imp_15min_once', 'expires_in' => 900],
        'd' => 'Token ≤ 15 minutes, single use. Guest writes blocked unless write_enabled.',
        'crit' => true,
        'e' => [403 => 'guest_write_blocked'],
    ]),
    ep('EP-AD-123', 'SP-17', 'POST', '/platform/support/users/{id}/resend-otp', 'platform', 'ad.support.resend_otp', [
        'name' => 'Resend OTP for user',
        'name_ar' => 'إعادة OTP لمستخدم',
        'b' => new stdClass(),
        'r' => ['success' => true],
    ]),
    ep('EP-AD-124', 'SP-17', 'POST', '/platform/support/users/{id}/revoke-sessions', 'platform', 'ad.support.revoke_sessions', [
        'name' => 'Revoke user sessions',
        'name_ar' => 'إنهاء جلسات المستخدم',
        'b' => ['reason' => 'جهاز ضائع'],
        'r' => ['revoked' => 3],
        'crit' => true,
    ]),
    ep('EP-AD-125A', 'SP-17', 'GET', '/platform/support/tickets', 'platform', 'ad.support.tickets', [
        'name' => 'List tickets',
        'name_ar' => 'التذاكر',
        'q' => listQuery(['filter[status]' => 'open', 'filter[priority]' => 'high']),
        'r' => [['id' => 512, 'source' => 'retailer_app', 'category' => 'sync', 'priority' => 'high', 'status' => 'open']],
    ]),
    ep('EP-AD-125B', 'SP-17', 'POST', '/platform/support/tickets', 'platform', 'ad.support.tickets', [
        'name' => 'Create ticket',
        'name_ar' => 'إنشاء تذكرة',
        'b' => [
            'source' => 'phone',
            'category' => 'payments',
            'priority' => 'high',
            'description' => 'التاجر دفع والمندوب لم يرَ الوصل',
            'attachments' => [],
            'assignee_id' => 4,
            'status' => 'open',
            'resolution' => null,
            'root_cause' => null,
        ],
        'r' => ['id' => 513],
    ]),

    ep('EP-AD-130', 'SP-17', 'GET', '/platform/system/queues', 'platform', 'ad.system.view', [
        'name' => 'Queue health',
        'name_ar' => 'طوابير النظام',
        'r' => [['name' => 'notifications', 'pending' => 12, 'processing' => 2, 'failed' => 1, 'avg_wait' => 1.4, 'workers' => 4]],
    ]),
    ep('EP-AD-131', 'SP-17', 'GET', '/platform/system/errors', 'platform', 'ad.system.view', [
        'name' => 'Recent exceptions',
        'name_ar' => 'آخر الاستثناءات',
        'r' => [['at' => '2026-03-01T09:01:00+03:00', 'class' => 'QueryException', 'message' => '...']],
        'd' => 'Last 100 exceptions.',
    ]),
    ep('EP-AD-132', 'SP-17', 'GET', '/platform/system/sync', 'platform', 'ad.system.view', [
        'name' => 'Sync health',
        'name_ar' => 'صحة المزامنة',
        'r' => ['pending_operations' => 12, 'oldest_unconfirmed' => '2026-03-01T08:50:00+03:00', 'conflicts' => []],
    ]),
    ep('EP-AD-133', 'SP-17', 'GET', '/platform/system/integrations', 'platform', 'ad.system.view', [
        'name' => 'Integrations health',
        'name_ar' => 'صحة التكاملات',
        'r' => [
            'whatsapp' => ['success_1h' => 0.992, 'success_24h' => 0.981, 'avg_latency' => 420],
            'sms' => ['success_1h' => 0.97, 'success_24h' => 0.96, 'avg_latency' => 800],
            'maps' => ['status' => 'ok'],
            'storage' => ['status' => 'ok'],
            'push' => ['status' => 'ok'],
            'errors' => [],
        ],
    ]),
    ep('EP-AD-134', 'SP-17', 'POST', '/platform/system/switch-otp-channel', 'platform', 'ad.system.switch_otp', [
        'name' => 'Switch OTP channel',
        'name_ar' => 'تبديل قناة OTP',
        'b' => ['channel' => 'sms'],
        'r' => ['channel' => 'sms'],
        'd' => 'whatsapp|sms — no redeploy (REQ-AD-076).',
        'crit' => true,
    ]),
    ep('EP-AD-135', 'SP-17', 'POST', '/platform/system/retry-jobs', 'platform', 'ad.system.retry_jobs', [
        'name' => 'Retry failed jobs',
        'name_ar' => 'إعادة مهام فاشلة',
        'b' => ['job_ids' => ['job_1', 'job_2']],
        'r' => ['queued' => 2],
    ]),
    ep('EP-AD-136', 'SP-17', 'POST', '/platform/system/maintenance', 'platform', 'ad.system.maintenance', [
        'name' => 'Maintenance mode',
        'name_ar' => 'وضع الصيانة',
        'b' => [
            'enabled' => true,
            'message_ar' => 'صيانة مجدولة حتى الساعة 04:00',
            'until' => '2026-03-02T04:00:00+03:00',
        ],
        'r' => ['enabled' => true],
        'dual' => true,
        'crit' => true,
    ]),
];
