<?php

declare(strict_types=1);

$productBody = [
    'name_ar' => 'زيت دوار الشمس 1 لتر',
    'name_en' => 'Sunflower Oil 1L',
    'sku' => 'OIL-SUN-1L',
    'brand_id' => 12,
    'category_id' => 340,
    'model_no' => 'SUN-1000',
    'barcode' => '6291000000000',
    'status' => 'active',
    'short_description' => 'زيت نباتي للطبخ',
    'long_description' => '<p>زيت دوار الشمس</p>',
    'specs' => [['key' => 'الحجم', 'value' => '1 لتر']],
    'media' => ['images' => ['media_id_1'], 'primary' => 'media_id_1', 'video' => null],
    'sale_unit_id' => 3,
    'unit_factors' => [['from_unit_id' => 3, 'to_unit_id' => 5, 'factor' => 12]],
    'min_order_qty' => 1,
    'order_multiple' => 1,
    'weight_gram' => 950,
    'pricing' => [
        'type' => 'tiered',
        'base_price' => 12000,
        'currency_id' => 1,
        'tiers' => [
            ['from' => 1, 'to' => 4, 'price' => 12000],
            ['from' => 5, 'to' => 9, 'price' => 11500],
            ['from' => 10, 'to' => null, 'price' => 11000],
        ],
    ],
    'inventory' => ['tracked' => true, 'reorder_point' => 50, 'allow_backorder' => false],
    'availability' => [
        'zone_ids' => [12, 13],
        'activity_type_ids' => [3, 4],
        'retailer_group_ids' => [],
        'lead_time_days' => 2,
    ],
    'marketing' => ['tags' => ['new'], 'sliders' => ['best_selling'], 'priority' => 10],
];

return [
    ep('EP-CH-001', 'SP-01', 'POST', '/channel/auth/request-otp', 'channel', null, [
        'name' => 'Channel request OTP',
        'name_ar' => 'طلب رمز دخول القناة',
        'auth' => false,
        'b' => ['phone' => '+963944000000'],
        'r' => ['otp_id' => 'otp_ch_1'],
        'e' => [429 => 'rate_limited'],
    ]),
    ep('EP-CH-002', 'SP-01', 'POST', '/channel/auth/verify-otp', 'channel', null, [
        'name' => 'Channel verify OTP',
        'name_ar' => 'تحقق دخول القناة',
        'auth' => false,
        'b' => ['otp_id' => '{{otp_id}}', 'code' => '482193'],
        'r' => [
            'token' => '20|channel_xxxxx',
            'channels' => [['id' => 1, 'name' => 'شركة النور']],
            'permissions' => ['sc.dashboard.view', 'sc.orders.view'],
        ],
        'd' => 'Returns channel list when the user belongs to more than one.',
    ]),

    ep('EP-SC-010A', 'SP-06', 'GET', '/channel/brands', 'channel', 'sc.catalog.view', [
        'name' => 'List brands',
        'name_ar' => 'العلامات',
        'q' => listQuery(['filter[status]' => 'active']),
        'r' => [['id' => 12, 'name_ar' => 'نور', 'name_en' => 'Nour', 'status' => 'active']],
    ]),
    ep('EP-SC-010B', 'SP-06', 'POST', '/channel/brands', 'channel', 'sc.catalog.create', [
        'name' => 'Create brand',
        'name_ar' => 'إنشاء علامة',
        'b' => [
            'name_ar' => 'نور',
            'name_en' => 'Nour',
            'logo' => 'media_logo_1',
            'banner' => 'media_banner_1',
            'description' => 'منتجات غذائية',
            'activity_type_ids' => [3],
            'order' => 1,
            'status' => 'active',
            'sliders' => [['name' => 'الأكثر مبيعاً', 'source' => 'algorithm', 'source_id' => null, 'count' => 12, 'order' => 1]],
        ],
        'r' => ['id' => 12],
    ]),
    ep('EP-SC-011', 'SP-06', 'GET', '/channel/categories/tree', 'channel', 'sc.catalog.view', [
        'name' => 'Category tree',
        'name_ar' => 'شجرة الفئات',
        'r' => [[
            'id' => 340,
            'name' => 'زيوت',
            'image' => null,
            'icon' => 'oil',
            'parent_id' => 10,
            'level' => 2,
            'order' => 1,
            'status' => 'active',
            'direct_products' => 14,
            'total_products' => 40,
            'children' => [],
        ]],
    ]),
    ep('EP-SC-012', 'SP-06', 'POST', '/channel/categories', 'channel', 'sc.catalog.create', [
        'name' => 'Create category',
        'name_ar' => 'إنشاء فئة',
        'b' => [
            'name' => 'زيوت نباتية',
            'parent_id' => 10,
            'image' => null,
            'icon' => 'oil',
            'order' => 1,
            'activity_type_ids' => [3],
        ],
        'r' => ['id' => 341],
        'e' => [422 => 'validation_failed'],
        'd' => '422 at the 6th level.',
    ]),
    ep('EP-SC-013', 'SP-06', 'POST', '/channel/categories/reorder', 'channel', 'sc.catalog.update', [
        'name' => 'Reorder categories',
        'name_ar' => 'إعادة ترتيب الفئات',
        'b' => ['moves' => [['id' => 341, 'parent_id' => 10, 'order' => 2]]],
        'r' => ['updated' => 1],
    ]),
    ep('EP-SC-014', 'SP-06', 'GET', '/channel/products', 'channel', 'sc.catalog.view', [
        'name' => 'List products',
        'name_ar' => 'المنتجات',
        'q' => listQuery([
            'search' => 'زيت',
            'filter[brand_id]' => '12',
            'filter[category_id]' => '340',
            'filter[status]' => 'active',
            'filter[zone_id]' => '12',
        ]),
        'r' => [['id' => 880, 'sku' => 'OIL-SUN-1L', 'name_ar' => 'زيت دوار الشمس 1 لتر', 'status' => 'active']],
    ]),
    ep('EP-SC-015', 'SP-06', 'POST', '/channel/products', 'channel', 'sc.catalog.create', [
        'name' => 'Create product',
        'name_ar' => 'إنشاء منتج',
        'b' => $productBody,
        'r' => ['id' => 880, 'sku' => 'OIL-SUN-1L'],
        'd' => 'All money fields are integer minor units (BR-AD-18). 12000 ≠ 120.00.',
    ]),
    ep('EP-SC-016', 'SP-06', 'PUT', '/channel/products/{id}', 'channel', 'sc.catalog.update', [
        'name' => 'Update product',
        'name_ar' => 'تحديث منتج',
        'b' => $productBody,
        'r' => ['id' => 880],
    ]),
    ep('EP-SC-017', 'SP-06', 'POST', '/channel/products/{id}/variants/generate', 'channel', 'sc.catalog.variants', [
        'name' => 'Generate variants',
        'name_ar' => 'توليد التباينات',
        'b' => ['axes' => [['name' => 'الحجم', 'values' => ['1L', '2L']]]],
        'r' => ['variants' => [
            ['id' => 1, 'sku' => 'OIL-SUN-1L', 'combination' => ['الحجم' => '1L'], 'price' => 12000, 'stock' => 80, 'barcode' => '6291000000000', 'image' => null],
        ]],
    ]),
    ep('EP-SC-018', 'SP-06', 'POST', '/channel/products/bulk', 'channel', 'sc.catalog.update', [
        'name' => 'Bulk product action',
        'name_ar' => 'إجراء جماعي على المنتجات',
        'b' => ['product_ids' => [880, 881], 'action' => 'activate', 'payload' => []],
        'r' => ['affected_count' => 2],
    ]),
    ep('EP-SC-019', 'SP-06', 'POST', '/channel/catalog/import', 'channel', 'sc.catalog.import', [
        'name' => 'Import catalog',
        'name_ar' => 'استيراد الكتالوج',
        'mp' => true,
        'b' => ['file' => null, 'type' => 'products', 'dry_run' => true],
        'r' => ['preview' => [], 'errors' => [['row' => 4, 'message' => 'sku exists']], 'duplicates' => ['OIL-SUN-1L']],
    ]),
    ep('EP-SC-020', 'SP-06', 'GET', '/channel/catalog/export', 'channel', 'sc.catalog.view', [
        'name' => 'Export catalog',
        'name_ar' => 'تصدير الكتالوج',
        'q' => ['filter[status]' => 'active'],
        'r' => ['job_id' => 'job_cat_exp_1'],
    ]),

    ep('EP-SC-030A', 'SP-07', 'GET', '/channel/price-lists', 'channel', 'sc.pricing.view', [
        'name' => 'List price lists',
        'name_ar' => 'قوائم الأسعار',
        'q' => listQuery(['filter[type]' => 'zone']),
        'r' => [['id' => 3, 'name' => 'المزة', 'type' => 'zone', 'status' => 'active']],
    ]),
    ep('EP-SC-030B', 'SP-07', 'POST', '/channel/price-lists', 'channel', 'sc.pricing.update', [
        'name' => 'Create price list',
        'name_ar' => 'إنشاء قائمة أسعار',
        'b' => [
            'name' => 'تجار المزة',
            'type' => 'zone',
            'zone_ids' => [12],
            'group_id' => null,
            'retailer_id' => null,
            'adjustment' => ['mode' => 'percent', 'value' => -5],
            'effective_from' => '2026-03-01T00:00:00+03:00',
            'effective_to' => null,
            'reason' => 'تسعير منطقة',
        ],
        'r' => ['id' => 3, 'status' => 'active'],
        'd' => 'type: base|zone|group|retailer. Precedence: retailer_price ← group_list ← zone_list ← qty_tier ← base_price.',
    ]),
    ep('EP-SC-031', 'SP-07', 'PUT', '/channel/products/{id}/pricing', 'channel', 'sc.pricing.update', [
        'name' => 'Update product pricing',
        'name_ar' => 'تسعير منتج',
        'b' => [
            'type' => 'tiered',
            'base_price' => 12000,
            'tiers' => [
                ['from' => 1, 'to' => 4, 'price' => 12000],
                ['from' => 5, 'to' => 9, 'price' => 11500],
                ['from' => 10, 'to' => null, 'price' => 11000],
            ],
            'reason' => 'تعديل شرائح الجملة',
        ],
        'r' => ['price_change_log_id' => 901],
    ]),
    ep('EP-SC-032', 'SP-07', 'POST', '/channel/price-lists/{id}/schedule', 'channel', 'sc.pricing.schedule', [
        'name' => 'Schedule price list',
        'name_ar' => 'جدولة قائمة أسعار',
        'b' => [
            'effective_from' => '2026-03-15T00:00:00+03:00',
            'changes' => [['product_id' => 880, 'base_price' => 11800]],
        ],
        'r' => ['scheduled_job_id' => 'job_price_15'],
    ]),
    ep('EP-SC-033', 'SP-07', 'POST', '/channel/pricing/bulk-update', 'channel', 'sc.pricing.update', [
        'name' => 'Bulk price update',
        'name_ar' => 'تحديث أسعار جماعي',
        'b' => ['product_ids' => [880, 881], 'mode' => 'percent', 'value' => 3, 'reason' => 'ارتفاع تكلفة'],
        'r' => ['affected_count' => 2],
    ]),
    ep('EP-SC-034', 'SP-07', 'GET', '/channel/pricing/change-log', 'channel', 'sc.pricing.view', [
        'name' => 'Pricing change log',
        'name_ar' => 'سجل تغيير الأسعار',
        'q' => listQuery(['filter[product_id]' => '880', 'filter[user_id]' => '10', 'filter[date]' => '2026-03-01']),
        'r' => [['at' => '2026-03-01T09:00:00+03:00', 'user' => 10, 'product' => 880, 'before' => 12000, 'after' => 11800, 'reason' => 'تعديل']],
    ]),
    ep('EP-SC-035', 'SP-07', 'PUT', '/channel/reps/{id}/discount-cap', 'channel', 'sc.reps.update', [
        'name' => 'Rep discount cap',
        'name_ar' => 'سقف خصم المندوب',
        'b' => ['max_discount_percent' => 5, 'max_cash_hold' => 5000000],
        'r' => ['rep' => ['id' => 70, 'max_discount_percent' => 5, 'max_cash_hold' => 5000000]],
        'd' => 'Exceeding cap at submit → 403 discount_cap_exceeded (BR-12).',
    ]),

    ep('EP-SC-040A', 'SP-08', 'GET', '/channel/offers', 'channel', 'sc.offers.view', [
        'name' => 'List offers',
        'name_ar' => 'العروض',
        'q' => listQuery(['filter[status]' => 'active', 'filter[type]' => 'buy_x_get_y']),
        'r' => [['id' => 44, 'name' => 'اشترِ 10 واحصل على 1', 'type' => 'buy_x_get_y', 'status' => 'active']],
    ]),
    ep('EP-SC-040B', 'SP-08', 'POST', '/channel/offers', 'channel', 'sc.offers.create', [
        'name' => 'Create offer',
        'name_ar' => 'إنشاء عرض',
        'b' => [
            'name' => 'اشترِ 10 واحصل على 1',
            'type' => 'buy_x_get_y',
            'media' => ['media_id_9'],
            'description' => 'على زيت دوار الشمس',
            'components' => [['product_id' => 880, 'qty' => 10]],
            'rules' => ['buy_qty' => 10, 'get_qty' => 1],
            'rewards' => ['product_id' => 880, 'qty' => 1],
            'targeting' => [
                'scope' => 'zones',
                'activity_type_ids' => [3],
                'zone_ids' => [12],
                'group_ids' => [],
                'retailer_ids' => [],
            ],
            'constraints' => [
                'starts_at' => '2026-03-01T00:00:00+03:00',
                'ends_at' => '2026-03-31T23:59:59+03:00',
                'total_qty' => 500,
                'per_retailer_max' => 3,
                'per_order_max' => 1,
                'min_invoice_value' => 0,
                'min_items' => 1,
            ],
            'stackable' => false,
            'priority' => 10,
            'status' => 'active',
        ],
        'r' => ['id' => 44],
        'd' => 'type: product_discount|invoice_discount|buy_x_get_y|bundle|tiered_discount|gift. Deleting a line in the offer removes the whole offer (BR-08).',
    ]),
    ep('EP-SC-041', 'SP-08', 'PATCH', '/channel/offers/{id}/stop', 'channel', 'sc.offers.stop', [
        'name' => 'Stop offer',
        'name_ar' => 'إيقاف عرض',
        'b' => ['reason' => 'نفاد الكمية المخصصة'],
        'r' => ['status' => 'stopped'],
    ]),
    ep('EP-SC-042', 'SP-08', 'GET', '/channel/offers/{id}/performance', 'channel', 'sc.offers.view', [
        'name' => 'Offer performance',
        'name_ar' => 'أداء العرض',
        'r' => [
            'applied_count' => 180,
            'linked_sales' => 21000000,
            'discount_given' => 1800000,
            'net_margin' => 4200000,
            'retailers_count' => 96,
            'by_zone' => [['zone_id' => 12, 'applied_count' => 80]],
            'conversion_rate' => 0.22,
        ],
    ]),
];
