<?php

declare(strict_types=1);

$productBody = [
    'name_ar' => 'زيت دوار الشمس 1 لتر',
    'name_en' => 'Sunflower Oil 1L',
    'sku' => 'OIL-SUN-1L',
    'brand_id' => 12,
    'category_id' => 340,
    'model_no' => 'SUN-1000',
    'barcode' => '6291000000000',
    'status' => 'active',
    'short_description' => 'زيت نباتي للطبخ',
    'long_description' => '<p>زيت دوار الشمس</p>',
    'specs' => [['key' => 'الحجم', 'value' => '1 لتر']],
    'media' => ['images' => ['media_id_1'], 'primary' => 'media_id_1', 'video' => null],
    'sale_unit_id' => 3,
    'unit_factors' => [['from_unit_id' => 3, 'to_unit_id' => 5, 'factor' => 12]],
    'min_order_qty' => 1,
    'order_multiple' => 1,
    'weight_gram' => 950,
    'length_mm' => 200,
    'width_mm' => 80,
    'height_mm' => 80,
    'pricing' => [
        'type' => 'tiered',
        'base_price' => 12000,
        'currency_id' => 1,
        'tax_percent' => 0,
        'tiers' => [
            ['from' => 1, 'to' => 4, 'price' => 12000],
            ['from' => 5, 'to' => 9, 'price' => 11500],
            ['from' => 10, 'to' => null, 'price' => 11000],
        ],
    ],
    'inventory' => [
        'tracked' => true,
        'reorder_point' => 50,
        'allow_backorder' => false,
        'opening_stock' => [['warehouse_id' => 1, 'qty' => 100]],
    ],
    'availability' => [
        'zone_ids' => [12, 13],
        'activity_type_ids' => [3, 4],
        'retailer_group_ids' => [],
        'lead_time_days' => 2,
    ],
    'marketing' => ['tags' => ['new'], 'sliders' => ['best_selling'], 'priority' => 10],
];

return [
    ep('EP-CH-001', 'SP-01', 'POST', '/channel/auth/request-otp', 'channel', null, [
        'name' => 'Channel request OTP',
        'name_ar' => 'طلب رمز دخول القناة',
        'auth' => false,
        'b' => ['phone' => '+963944000000'],
        'r' => ['otp_id' => 'otp_ch_1'],
        'e' => [429 => 'rate_limited'],
    ]),
    ep('EP-CH-002', 'SP-01', 'POST', '/channel/auth/verify-otp', 'channel', null, [
        'name' => 'Channel verify OTP',
        'name_ar' => 'تحقق دخول القناة',
        'auth' => false,
        'b' => ['otp_id' => '{{otp_id}}', 'code' => '482193'],
        'r' => [
            'token' => '20|channel_xxxxx',
            'channels' => [['id' => 1, 'name' => 'شركة النور']],
            'permissions' => ['sc.dashboard.view', 'sc.orders.view'],
        ],
        'd' => 'Returns channel list when the user belongs to more than one.',
    ]),

    ep('EP-SC-010A', 'SP-06', 'GET', '/channel/brands', 'channel', 'sc.catalog.view', [
        'name' => 'List brands',
        'name_ar' => 'العلامات',
        'q' => listQuery([
            'filter[status]' => 'active',
            'filter[activity_type_id]' => '3',
            'filter[search]' => 'نور',
            'sort' => 'order',
        ]),
        'r' => [['id' => 12, 'name_ar' => 'نور', 'name_en' => 'Nour', 'status' => 'active', 'order' => 1]],
        'd' => 'Thin list. Filters: filter[status], filter[activity_type_id], filter[search] (name_ar|name_en). Default sort order.',
    ]),
    ep('EP-SC-010B', 'SP-06', 'POST', '/channel/brands', 'channel', 'sc.catalog.create', [
        'name' => 'Create brand',
        'name_ar' => 'إنشاء علامة',
        'b' => [
            'name_ar' => 'نور',
            'name_en' => 'Nour',
            'logo' => '42',
            'banner' => '43',
            'description' => 'منتجات غذائية',
            'activity_type_ids' => [3],
            'order' => 1,
            'status' => 'active',
            'sliders' => [['name' => 'الأكثر مبيعاً', 'source' => 'algorithm', 'source_id' => null, 'count' => 12, 'order' => 1]],
        ],
        'r' => ['id' => 12],
        'e' => [422 => 'validation_failed'],
        'd' => 'logo required (media_id from EP-SC-021); square image ≥512×512. description required ≤300. activity_type_ids required ≥1. name_ar unique per channel. status active|disabled. sliders.source ∈ algorithm|manual. banner optional media_id.',
    ]),
    ep('EP-SC-010C', 'SP-06', 'GET', '/channel/brands/{id}', 'channel', 'sc.catalog.view', [
        'name' => 'Brand detail',
        'name_ar' => 'تفاصيل علامة',
        'r' => [
            'id' => 12,
            'name_ar' => 'نور',
            'name_en' => 'Nour',
            'logo' => '42',
            'logo_url' => 'https://cdn.example/media/42.jpg',
            'banner' => '43',
            'banner_url' => 'https://cdn.example/media/43.jpg',
            'description' => 'منتجات غذائية',
            'activity_type_ids' => [3],
            'order' => 1,
            'status' => 'active',
            'sliders' => [['id' => 1, 'name' => 'الأكثر مبيعاً', 'source' => 'algorithm', 'source_id' => null, 'count' => 12, 'order' => 1]],
        ],
        'd' => 'Full editor body. logo/banner are media_id strings; logo_url/banner_url are resolved. Foreign or other-channel id → 404.',
    ]),
    ep('EP-SC-010D', 'SP-06', 'PUT', '/channel/brands/{id}', 'channel', 'sc.catalog.update', [
        'name' => 'Update brand',
        'name_ar' => 'تحديث علامة',
        'b' => [
            'name_ar' => 'نور',
            'name_en' => 'Nour',
            'logo' => '42',
            'banner' => '43',
            'description' => 'منتجات غذائية',
            'activity_type_ids' => [3],
            'order' => 1,
            'status' => 'disabled',
            'sliders' => [['name' => 'الأكثر مبيعاً', 'source' => 'algorithm', 'source_id' => null, 'count' => 12, 'order' => 1]],
        ],
        'r' => ['id' => 12],
        'e' => [422 => 'validation_failed'],
        'd' => 'Same body as create. status=disabled hides the brand and its products from retailer/rep APIs without deleting channel data. sliders[] replaces the full set.',
    ]),
    ep('EP-SC-011', 'SP-06', 'GET', '/channel/categories/tree', 'channel', 'sc.catalog.view', [
        'name' => 'Category tree',
        'name_ar' => 'شجرة الفئات',
        'r' => [[
            'id' => 340,
            'name' => 'زيوت',
            'image' => null,
            'icon' => 'oil',
            'parent_id' => 10,
            'level' => 2,
            'order' => 1,
            'status' => 'active',
            'direct_products' => 14,
            'total_products' => 40,
            'description' => 'زيوت الطبخ',
            'children' => [],
        ]],
        'd' => 'Platform root categories (level 1) plus any channel-owned roots (parent_id null). description is null on platform roots.',
    ]),
    ep('EP-SC-012', 'SP-06', 'POST', '/channel/categories', 'channel', 'sc.catalog.create', [
        'name' => 'Create category',
        'name_ar' => 'إنشاء فئة',
        'b' => [
            'name' => 'زيوت نباتية',
            'parent_id' => 10,
            'description' => 'زيوت الطبخ',
            'image' => null,
            'icon' => 'oil',
            'order' => 1,
            'activity_type_ids' => [3],
        ],
        'r' => ['id' => 341],
        'e' => [422 => 'validation_failed'],
        'd' => 'parent_id optional: omit or null to create a channel-owned root (level 1). Platform roots remain available as parents. 422 at the 6th level.',
    ]),
    ep('EP-SC-012A', 'SP-06', 'PUT', '/channel/categories/{id}', 'channel', 'sc.catalog.update', [
        'name' => 'Update category',
        'name_ar' => 'تعديل فئة',
        'b' => [
            'name' => 'زيوت نباتية',
            'description' => 'زيوت الطبخ',
            'image' => '42',
            'icon' => 'oil',
            'order' => 2,
            'activity_type_ids' => [3, 4],
        ],
        'r' => ['id' => 341],
        'e' => [404 => 'not_found', 422 => 'validation_failed'],
        'd' => 'Does not move the node (use reorder) and does not change status (use PATCH …/status). image is a media_id string from EP-SC-021.',
    ]),
    ep('EP-SC-012B', 'SP-06', 'PATCH', '/channel/categories/{id}/status', 'channel', 'sc.catalog.update', [
        'name' => 'Change category status',
        'name_ar' => 'تعطيل/تفعيل فئة',
        'b' => ['status' => 'disabled', 'reason' => 'دمج فئات'],
        'r' => ['id' => 341, 'status' => 'disabled'],
        'e' => [404 => 'not_found', 422 => 'ref_in_use'],
        'd' => 'Disable refused while the category (or any descendant) has active products or child categories — details.affected.{child_categories,active_products}. Soft disable only; no hard delete.',
    ]),
    ep('EP-SC-013', 'SP-06', 'POST', '/channel/categories/reorder', 'channel', 'sc.catalog.update', [
        'name' => 'Reorder categories',
        'name_ar' => 'إعادة ترتيب الفئات',
        'b' => ['moves' => [['id' => 341, 'parent_id' => 10, 'order' => 2]]],
        'r' => ['updated' => 1],
    ]),
    ep('EP-SC-014', 'SP-06', 'GET', '/channel/products', 'channel', 'sc.catalog.view', [
        'name' => 'List products',
        'name_ar' => 'المنتجات',
        'q' => listQuery([
            'search' => 'زيت',
            'filter[brand_id]' => '12',
            'filter[category_id]' => '340',
            'filter[status]' => 'active',
            'filter[zone_id]' => '12',
        ]),
        'r' => [['id' => 880, 'sku' => 'OIL-SUN-1L', 'name_ar' => 'زيت دوار الشمس 1 لتر', 'status' => 'active']],
    ]),
    ep('EP-SC-014A', 'SP-06', 'GET', '/channel/products/{id}', 'channel', 'sc.catalog.view', [
        'name' => 'Product detail',
        'name_ar' => 'تفاصيل منتج',
        'r' => array_merge($productBody, [
            'id' => 880,
            'axes' => [['name' => 'الحجم', 'values' => ['1L', '2L']]],
            'variants' => [[
                'id' => 1,
                'sku' => 'OIL-SUN-1L-1L',
                'combination' => ['الحجم' => '1L'],
                'barcode' => '6291000000001',
                'image' => null,
                'status' => 'active',
                'price_override' => null,
                'price' => 12000,
                'stock' => 0,
            ]],
        ]),
        'd' => 'Full create/update body for the editor. pricing may be null when unset — use PUT /products/{id}/pricing. axes/variants from generate. Non-empty barcode must be unique within the channel (product or variant). Foreign or other-channel id → 404.',
    ]),
    ep('EP-SC-015', 'SP-06', 'POST', '/channel/products', 'channel', 'sc.catalog.create', [
        'name' => 'Create product',
        'name_ar' => 'إنشاء منتج',
        'b' => $productBody,
        'r' => ['id' => 880, 'sku' => 'OIL-SUN-1L'],
        'd' => 'All money fields are integer minor units (BR-AD-18). 12000 ≠ 120.00.',
    ]),
    ep('EP-SC-016', 'SP-06', 'PUT', '/channel/products/{id}', 'channel', 'sc.catalog.update', [
        'name' => 'Update product',
        'name_ar' => 'تحديث منتج',
        'b' => $productBody,
        'r' => ['id' => 880],
    ]),
    ep('EP-SC-016A', 'SP-06', 'POST', '/channel/products/{id}/duplicate', 'channel', 'sc.catalog.create', [
        'name' => 'Duplicate product',
        'name_ar' => 'نسخ منتج',
        'b' => ['sku' => 'OIL-SUN-1L-COPY', 'name_ar' => 'زيت دوار الشمس (نسخة)'],
        'r' => ['id' => 881, 'sku' => 'OIL-SUN-1L-COPY'],
        'e' => [422 => 'validation_failed'],
        'd' => 'Clones product children (specs/media/units/zones/activities/groups/sliders/tags/inventory flags) and product pricing. Does not copy variants — regenerate via EP-SC-017. sku required and unique.',
    ]),
    ep('EP-SC-017', 'SP-06', 'POST', '/channel/products/{id}/variants/generate', 'channel', 'sc.catalog.variants', [
        'name' => 'Generate variants',
        'name_ar' => 'توليد التباينات',
        'b' => ['axes' => [['name' => 'الحجم', 'values' => ['1L', '2L']]]],
        'r' => ['variants' => [
            [
                'id' => 1,
                'sku' => 'OIL-SUN-1L-1L',
                'combination' => ['الحجم' => '1L'],
                'price' => 12000,
                'stock' => 0,
                'barcode' => null,
                'image' => null,
                'status' => 'active',
                'price_override' => null,
            ],
        ]],
        'd' => 'Cartesian regenerate. Existing variants matched by SKU keep barcode/image/price_override; unmatched SKUs are deleted.',
    ]),
    ep('EP-SC-017A', 'SP-06', 'PUT', '/channel/products/{id}/variants/{variantId}', 'channel', 'sc.catalog.variants', [
        'name' => 'Update variant',
        'name_ar' => 'تحديث توليفة',
        'b' => [
            'sku' => 'OIL-SUN-1L-1L',
            'barcode' => '6291000000001',
            'image' => 'media_var_1',
            'status' => 'active',
            'price_override' => 12500,
            'warehouse_id' => 1,
            'stock' => 40,
        ],
        'r' => [
            'id' => 1,
            'sku' => 'OIL-SUN-1L-1L',
            'combination' => ['الحجم' => '1L'],
            'price' => 12500,
            'stock' => 40,
            'barcode' => '6291000000001',
            'image' => 'media_var_1',
            'status' => 'active',
            'price_override' => 12500,
        ],
        'e' => [404 => 'not_found', 422 => 'validation_failed'],
        'd' => 'price_override null clears inheritance override. Non-empty barcode unique within channel. stock+warehouse_id sets absolute on_hand for that warehouse (omit both to leave inventory untouched).',
    ]),
    ep('EP-SC-017B', 'SP-06', 'DELETE', '/channel/products/{id}/variants/{variantId}', 'channel', 'sc.catalog.variants', [
        'name' => 'Delete variant',
        'name_ar' => 'حذف توليفة',
        'r' => ['deleted' => true],
        'e' => [404 => 'not_found'],
        'd' => 'Deletes one combination without regenerating axes.',
    ]),
    ep('EP-SC-018', 'SP-06', 'POST', '/channel/products/bulk', 'channel', 'sc.catalog.update', [
        'name' => 'Bulk product action',
        'name_ar' => 'إجراء جماعي على المنتجات',
        'b' => [
            'product_ids' => [880, 881],
            'action' => 'set_category',
            'payload' => ['category_id' => 340],
        ],
        'r' => ['affected_count' => 2],
        'd' => 'action ∈ activate|disable|delete_draft|set_category|set_brand|set_zones|set_status. Cap 200. Price % stays EP-SC-033. payload.category_id / brand_id / zone_ids / status required per action.',
    ]),
    ep('EP-SC-019', 'SP-06', 'POST', '/channel/catalog/import', 'channel', 'sc.catalog.import', [
        'name' => 'Import catalog',
        'name_ar' => 'استيراد الكتالوج',
        'mp' => true,
        'b' => ['file' => null, 'type' => 'products', 'dry_run' => true],
        'r' => [
            'preview' => [['sku' => 'OIL-SUN-1L', 'name_ar' => 'زيت', 'status' => 'draft']],
            'errors' => [['row' => 4, 'message' => 'sku exists']],
            'duplicates' => ['OIL-SUN-1L'],
        ],
        'd' => 'Columns: sku,name_ar,name_en,barcode,brand_id,category_id,status,base_price,currency_id. Multipart only.',
    ]),
    ep('EP-SC-019A', 'SP-06', 'GET', '/channel/catalog/import/template', 'channel', 'sc.catalog.import', [
        'name' => 'Catalog import template',
        'name_ar' => 'قالب استيراد الكتالوج',
        'r' => [
            'columns' => ['sku', 'name_ar', 'name_en', 'barcode', 'brand_id', 'category_id', 'status', 'base_price', 'currency_id'],
            'sample_row' => [
                'sku' => 'OIL-SUN-1L',
                'name_ar' => 'زيت دوار الشمس',
                'name_en' => 'Sunflower Oil',
                'barcode' => '6291000000000',
                'brand_id' => 12,
                'category_id' => 340,
                'status' => 'draft',
                'base_price' => 12000,
                'currency_id' => 1,
            ],
        ],
    ]),
    ep('EP-SC-020', 'SP-06', 'GET', '/channel/catalog/export', 'channel', 'sc.catalog.view', [
        'name' => 'Export catalog',
        'name_ar' => 'تصدير الكتالوج',
        'q' => ['filter[status]' => 'active'],
        'r' => ['job_id' => 'job_cat_exp_1'],
        'd' => 'Async CSV with the same columns as import. Returns job_id only.',
    ]),
    ep('EP-SC-021', 'SP-06', 'POST', '/channel/media/upload', 'channel', 'sc.catalog.create', [
        'name' => 'Upload media',
        'name_ar' => 'رفع وسائط',
        'mp' => true,
        'b' => ['file' => null, 'type' => 'image'],
        'r' => [
            'media_id' => '42',
            'url' => 'https://cdn.example/media/42.jpg',
            'type' => 'image',
            'mime' => 'image/jpeg',
            'size' => 184320,
        ],
        'e' => [422 => 'validation_failed'],
        'd' => 'Multipart only. type ∈ image|video. Returns media_id + url for product/brand/category fields. Max image 8MB, video 50MB. Brand logos (used in EP-SC-010B/D) must be square ≥512×512 — validated on brand write.',
    ]),

    ep('EP-SC-030A', 'SP-07', 'GET', '/channel/price-lists', 'channel', 'sc.pricing.view', [
        'name' => 'List price lists',
        'name_ar' => 'قوائم الأسعار',
        'q' => listQuery(['filter[type]' => 'zone']),
        'r' => [['id' => 3, 'name' => 'المزة', 'type' => 'zone', 'status' => 'active']],
    ]),
    ep('EP-SC-030B', 'SP-07', 'POST', '/channel/price-lists', 'channel', 'sc.pricing.update', [
        'name' => 'Create price list',
        'name_ar' => 'إنشاء قائمة أسعار',
        'b' => [
            'name' => 'تجار المزة',
            'type' => 'zone',
            'zone_ids' => [12],
            'group_id' => null,
            'retailer_id' => null,
            'adjustment' => ['mode' => 'percent', 'value' => -5],
            'effective_from' => '2026-03-01T00:00:00+03:00',
            'effective_to' => null,
            'reason' => 'تسعير منطقة',
        ],
        'r' => ['id' => 3, 'status' => 'active'],
        'd' => 'type: base|zone|group|retailer. Precedence: retailer_price ← group_list ← zone_list ← qty_tier ← base_price.',
    ]),
    ep('EP-SC-031', 'SP-07', 'PUT', '/channel/products/{id}/pricing', 'channel', 'sc.pricing.update', [
        'name' => 'Update product pricing',
        'name_ar' => 'تسعير منتج',
        'b' => [
            'type' => 'tiered',
            'base_price' => 12000,
            'tiers' => [
                ['from' => 1, 'to' => 4, 'price' => 12000],
                ['from' => 5, 'to' => 9, 'price' => 11500],
                ['from' => 10, 'to' => null, 'price' => 11000],
            ],
            'reason' => 'تعديل شرائح الجملة',
        ],
        'r' => ['price_change_log_id' => 901],
    ]),
    ep('EP-SC-032', 'SP-07', 'POST', '/channel/price-lists/{id}/schedule', 'channel', 'sc.pricing.schedule', [
        'name' => 'Schedule price list',
        'name_ar' => 'جدولة قائمة أسعار',
        'b' => [
            'effective_from' => '2026-03-15T00:00:00+03:00',
            'changes' => [['product_id' => 880, 'base_price' => 11800]],
        ],
        'r' => ['scheduled_job_id' => 'job_price_15'],
    ]),
    ep('EP-SC-033', 'SP-07', 'POST', '/channel/pricing/bulk-update', 'channel', 'sc.pricing.update', [
        'name' => 'Bulk price update',
        'name_ar' => 'تحديث أسعار جماعي',
        'b' => ['product_ids' => [880, 881], 'mode' => 'percent', 'value' => 3, 'reason' => 'ارتفاع تكلفة'],
        'r' => ['affected_count' => 2],
    ]),
    ep('EP-SC-034', 'SP-07', 'GET', '/channel/pricing/change-log', 'channel', 'sc.pricing.view', [
        'name' => 'Pricing change log',
        'name_ar' => 'سجل تغيير الأسعار',
        'q' => listQuery(['filter[product_id]' => '880', 'filter[user_id]' => '10', 'filter[date]' => '2026-03-01']),
        'r' => [['at' => '2026-03-01T09:00:00+03:00', 'user' => 10, 'product' => 880, 'before' => 12000, 'after' => 11800, 'reason' => 'تعديل']],
    ]),
    ep('EP-SC-035', 'SP-07', 'PUT', '/channel/reps/{id}/discount-cap', 'channel', 'sc.reps.update', [
        'name' => 'Rep discount cap',
        'name_ar' => 'سقف خصم المندوب',
        'b' => ['max_discount_percent' => 5, 'max_cash_hold' => 5000000],
        'r' => ['rep' => ['id' => 70, 'max_discount_percent' => 5, 'max_cash_hold' => 5000000]],
        'd' => 'Exceeding cap at submit → 403 discount_cap_exceeded (BR-12).',
    ]),

    ep('EP-SC-040A', 'SP-08', 'GET', '/channel/offers', 'channel', 'sc.offers.view', [
        'name' => 'List offers',
        'name_ar' => 'العروض',
        'q' => listQuery(['filter[status]' => 'active', 'filter[type]' => 'buy_x_get_y']),
        'r' => [['id' => 44, 'name' => 'اشترِ 10 واحصل على 1', 'type' => 'buy_x_get_y', 'status' => 'active']],
    ]),
    ep('EP-SC-040B', 'SP-08', 'POST', '/channel/offers', 'channel', 'sc.offers.create', [
        'name' => 'Create offer',
        'name_ar' => 'إنشاء عرض',
        'b' => [
            'name' => 'اشترِ 10 واحصل على 1',
            'type' => 'buy_x_get_y',
            'media' => ['media_id_9'],
            'description' => 'على زيت دوار الشمس',
            'components' => [['product_id' => 880, 'qty' => 10]],
            'rules' => ['buy_qty' => 10, 'get_qty' => 1],
            'rewards' => ['product_id' => 880, 'qty' => 1],
            'targeting' => [
                'scope' => 'zones',
                'activity_type_ids' => [3],
                'zone_ids' => [12],
                'group_ids' => [],
                'retailer_ids' => [],
            ],
            'constraints' => [
                'starts_at' => '2026-03-01T00:00:00+03:00',
                'ends_at' => '2026-03-31T23:59:59+03:00',
                'total_qty' => 500,
                'per_retailer_max' => 3,
                'per_order_max' => 1,
                'min_invoice_value' => 0,
                'min_items' => 1,
            ],
            'stackable' => false,
            'priority' => 10,
            'status' => 'active',
        ],
        'r' => ['id' => 44],
        'd' => 'type: product_discount|invoice_discount|buy_x_get_y|bundle|tiered_discount|gift. Deleting a line in the offer removes the whole offer (BR-08).',
    ]),
    ep('EP-SC-041', 'SP-08', 'PATCH', '/channel/offers/{id}/stop', 'channel', 'sc.offers.stop', [
        'name' => 'Stop offer',
        'name_ar' => 'إيقاف عرض',
        'b' => ['reason' => 'نفاد الكمية المخصصة'],
        'r' => ['status' => 'stopped'],
    ]),
    ep('EP-SC-042', 'SP-08', 'GET', '/channel/offers/{id}/performance', 'channel', 'sc.offers.view', [
        'name' => 'Offer performance',
        'name_ar' => 'أداء العرض',
        'r' => [
            'applied_count' => 180,
            'linked_sales' => 21000000,
            'discount_given' => 1800000,
            'net_margin' => 4200000,
            'retailers_count' => 96,
            'by_zone' => [['zone_id' => 12, 'applied_count' => 80]],
            'conversion_rate' => 0.22,
        ],
    ]),
];
