<?php

declare(strict_types=1);

return [
    ep('EP-SC-050', 'SP-09', 'GET', '/channel/inventory/levels', 'channel', 'sc.inventory.view', [
        'name' => 'Stock levels',
        'name_ar' => 'أرصدة المخزون',
        'q' => listQuery(['filter[warehouse_id]' => '1', 'filter[product_id]' => '880']),
        'r' => [[
            'product' => ['id' => 880, 'name_ar' => 'زيت دوار الشمس 1 لتر'],
            'variant' => null,
            'warehouse' => ['id' => 1, 'name' => 'مستودع المزة'],
            'available' => 420,
            'reserved' => 30,
            'in_transit' => 12,
            'damaged' => 2,
        ]],
    ]),
    ep('EP-SC-051', 'SP-09', 'POST', '/channel/inventory/adjust', 'channel', 'sc.inventory.adjust', [
        'name' => 'Adjust inventory',
        'name_ar' => 'تسوية مخزون',
        'b' => [
            'product_id' => 880,
            'variant_id' => null,
            'warehouse_id' => 1,
            'qty_delta' => -3,
            'reason' => 'تلف أثناء التخزين',
        ],
        'r' => ['movement_id' => 7001, 'available' => 417],
        'dual' => true,
        'crit' => true,
    ]),
    ep('EP-SC-052', 'SP-09', 'POST', '/channel/inventory/transfers', 'channel', 'sc.inventory.transfer', [
        'name' => 'Create transfer',
        'name_ar' => 'تحويل مخزون',
        'b' => [
            'from_warehouse_id' => 1,
            'to_warehouse_id' => 2,
            'lines' => [['product_id' => 880, 'variant_id' => null, 'qty' => 20]],
        ],
        'r' => ['id' => 55, 'status' => 'sent'],
        'd' => 'Statuses: sent then received.',
    ]),
    ep('EP-SC-052A', 'SP-09', 'GET', '/channel/inventory/transfers', 'channel', 'sc.inventory.transfer', [
        'name' => 'List transfers',
        'name_ar' => 'تحويلات المخزون',
        'q' => listQuery(['filter[status]' => 'sent', 'filter[warehouse_id]' => '1']),
        'r' => [[
            'id' => 55,
            'from_warehouse_id' => 1,
            'to_warehouse_id' => 2,
            'status' => 'sent',
            'lines_count' => 1,
            'created_at' => '2026-03-01T09:00:00+03:00',
        ]],
        'd' => 'filter[warehouse_id] matches from or to. Paginated.',
    ]),
    ep('EP-SC-053', 'SP-09', 'GET', '/channel/inventory/movements', 'channel', 'sc.inventory.view', [
        'name' => 'Inventory movements',
        'name_ar' => 'حركة المخزون',
        'q' => listQuery(['filter[product_id]' => '880', 'filter[warehouse_id]' => '1']),
        'r' => [['id' => 7001, 'at' => '2026-03-01T09:00:00+03:00', 'type' => 'adjust', 'qty_before' => 420, 'qty_after' => 417]],
        'd' => 'Immutable ledger with balance before/after.',
    ]),
    ep('EP-SC-054', 'SP-09', 'PUT', '/channel/inventory/reorder-points', 'channel', 'sc.inventory.reorder', [
        'name' => 'Update reorder points',
        'name_ar' => 'نقاط إعادة الطلب',
        'b' => ['items' => [['product_id' => 880, 'warehouse_id' => 1, 'point' => 50]]],
        'r' => ['updated' => 1],
    ]),

    ep('EP-SC-060', 'SP-10', 'GET', '/channel/sub-orders', 'channel', 'sc.orders.view', [
        'name' => 'List sub-orders',
        'name_ar' => 'الطلبات الفرعية',
        'q' => listQuery([
            'filter[status]' => 'pending',
            'filter[zone_id]' => '12',
            'filter[retailer_id]' => '481',
            'filter[rep_id]' => '70',
            'filter[source]' => 'retailer_app',
            'filter[waiting_over_minutes]' => '30',
            'sort' => 'created_at',
        ]),
        'r' => [['id' => 9001, 'sub_order_no' => 'SO-9001', 'status' => 'pending', 'zone_id' => 12, 'total' => 48000]],
        'd' => 'Grouped by zone with warning colors in UI.',
        'in' => 'REQ-IN-06 hide supply_channel until confirmed',
    ]),
    ep('EP-SC-061', 'SP-10', 'GET', '/channel/sub-orders/{id}', 'channel', 'sc.orders.view', [
        'name' => 'Sub-order detail',
        'name_ar' => 'تفاصيل طلب فرعي',
        'r' => [
            'header' => ['sub_order_no' => 'SO-9001', 'status' => 'pending', 'shop' => 'بقالية النور'],
            'lines' => [['id' => 1, 'product_id' => 880, 'qty' => 4, 'unit_price' => 12000]],
            'financials' => ['subtotal' => 48000, 'discount' => 0, 'total' => 48000],
            'note' => null,
            'timeline' => [['stage' => 'pending', 'at' => '2026-03-01T09:10:00+03:00']],
            'allowed_actions' => ['confirm', 'reject', 'edit_lines'],
        ],
    ]),
    ep('EP-SC-062', 'SP-10', 'POST', '/channel/sub-orders/{id}/confirm', 'channel', 'sc.orders.confirm', [
        'name' => 'Confirm sub-order',
        'name_ar' => 'تأكيد طلب',
        'b' => new stdClass(),
        'r' => ['status' => 'confirmed', 'picking_list_id' => 301],
        'e' => [409 => 'illegal_transition', 423 => 'credit_limit_exceeded'],
        'd' => 'Reserves stock, creates picking list, reveals channel name to retailer.',
        'in' => 'REQ-IN-06',
    ]),
    ep('EP-SC-063', 'SP-10', 'POST', '/channel/sub-orders/bulk-confirm', 'channel', 'sc.orders.confirm', [
        'name' => 'Bulk confirm',
        'name_ar' => 'تأكيد جماعي',
        'b' => ['ids' => [9001, 9002, 9003]],
        'r' => ['confirmed' => [9001, 9002], 'failed' => [['id' => 9003, 'error' => 'credit_limit_exceeded']]],
        'd' => 'Up to 50 ids. Target: 50 orders under 2 minutes.',
    ]),
    ep('EP-SC-064', 'SP-10', 'POST', '/channel/sub-orders/{id}/reject', 'channel', 'sc.orders.reject', [
        'name' => 'Reject sub-order',
        'name_ar' => 'رفض طلب',
        'b' => ['reason' => 'خارج التغطية اليوم'],
        'r' => ['status' => 'rejected'],
        'd' => 'Immediate retailer notification.',
    ]),
    ep('EP-SC-065', 'SP-10', 'PATCH', '/channel/sub-orders/{id}/lines', 'channel', 'sc.orders.edit_lines', [
        'name' => 'Edit sub-order lines',
        'name_ar' => 'تعديل بنود الطلب',
        'b' => [
            'changes' => [['line_id' => 1, 'qty' => 3, 'removed' => false]],
            'reason' => 'نقص صنف',
        ],
        'r' => ['status' => 'confirmed', 'total' => 36000],
        'd' => 'Mandatory retailer notification.',
    ]),
    ep('EP-SC-066', 'SP-10', 'POST', '/channel/sub-orders/assign', 'channel', 'sc.orders.assign', [
        'name' => 'Assign to rep',
        'name_ar' => 'إسناد لمندوب',
        'b' => [
            'sub_order_ids' => [9001],
            'rep_id' => 70,
            'mode' => 'manual',
        ],
        'r' => ['assigned' => [9001]],
        'e' => [422 => 'validation_failed'],
        'd' => 'mode: manual|auto|bulk_zone. auto picks the first on-duty rep covering the sub-order zone; bulk_zone assigns every confirmed/postponed sub-order in zone_id (or the first id\'s zone) to rep_id or that on-duty rep. 422 if no on-duty rep covers the zone (BR-19).',
        'in' => 'REQ-IN-03',
    ]),
    ep('EP-SC-067', 'SP-10', 'POST', '/channel/sub-orders/{id}/reassign', 'channel', 'sc.orders.reassign', [
        'name' => 'Reassign sub-order',
        'name_ar' => 'إعادة إسناد',
        'b' => ['rep_id' => 71, 'reason' => 'المندوب خارج الخدمة'],
        'r' => ['status' => 'assigned'],
        'e' => [409 => 'illegal_transition'],
        'd' => 'Forbidden after handover is received.',
    ]),
    ep('EP-SC-068', 'SP-10', 'POST', '/channel/sub-orders/{id}/schedule', 'channel', 'sc.orders.schedule', [
        'name' => 'Schedule sub-order',
        'name_ar' => 'جدولة طلب',
        'b' => ['scheduled_at' => '2026-03-02T10:00:00+03:00', 'reason' => 'طلب التاجر'],
        'r' => ['status' => 'postponed', 'scheduled_at' => '2026-03-02T10:00:00+03:00'],
        'd' => 'Synced to the rep calendar.',
    ]),
    ep('EP-SC-069', 'SP-10', 'POST', '/channel/sub-orders/{id}/cancel', 'channel', 'sc.orders.cancel', [
        'name' => 'Cancel sub-order',
        'name_ar' => 'إلغاء طلب',
        'b' => ['reason' => 'طلب التاجر عبر الهاتف'],
        'r' => ['status' => 'cancelled'],
        'crit' => true,
        'd' => 'Releases reservation.',
        'e' => [409 => 'illegal_transition'],
    ]),

    ep('EP-SC-070', 'SP-12', 'GET', '/channel/return-requests', 'channel', 'sc.returns.view', [
        'name' => 'List return requests',
        'name_ar' => 'طلبات الإرجاع',
        'q' => listQuery([
            'filter[type]' => 'return',
            'filter[status]' => 'pending',
            'filter[rep_id]' => '70',
            'filter[zone_id]' => '12',
        ]),
        'r' => [[
            'id' => 200,
            'request_no' => 'RR-200',
            'type' => 'return',
            'status' => 'pending',
            'sla_due_at' => '2026-03-02T12:00:00+03:00',
            'overdue' => false,
        ]],
        'd' => 'sla_due_at set on create from channel settings.returns_sla_hours (default 24). overdue when pending/approved and sla_due_at < now.',
        'in' => 'REQ-IN-04',
    ]),
    ep('EP-SC-071', 'SP-12', 'POST', '/channel/return-requests/{id}/decide', 'channel', 'sc.returns.decide', [
        'name' => 'Decide return request',
        'name_ar' => 'قرار الإرجاع',
        'b' => ['decision' => 'approve', 'reason' => 'تلف ظاهر عند التسليم'],
        'r' => ['status' => 'approved'],
        'd' => 'Financial and stock impact per BR-13. decision: approve|reject.',
        'in' => 'REQ-IN-04',
    ]),
    ep('EP-SC-162', 'SP-12', 'POST', '/channel/return-requests/{id}/escalate', 'channel', 'sc.returns.decide', [
        'name' => 'Escalate overdue return SLA',
        'name_ar' => 'تصعيد مرتجع متأخر',
        'b' => ['message' => 'تجاوز SLA'],
        'r' => ['id' => 1, 'overdue' => true, 'escalated_at' => '2026-09-24T12:00:00+03:00', 'notified' => true],
        'd' => 'Only open+overdue return requests. Records audit and notifies channel managers via inbox/notification path.',
    ]),

    ep('EP-SC-075', 'SP-06', 'GET', '/channel/reps', 'channel', 'sc.reps.view', [
        'name' => 'List reps',
        'name_ar' => 'قائمة المندوبين',
        'q' => listQuery(['filter[status]' => 'pending_review']),
        'r' => [[
            'id' => 70,
            'name' => 'أحمد المندوب',
            'phone' => '+963933000070',
            'status' => 'active',
            'zone_ids' => [12],
            'on_duty' => true,
            'max_discount_percent' => 5,
            'max_cash_hold' => 5000000,
        ]],
        'd' => 'id is AppUser id (same as assign / settle / discount-cap). status: pending_review|active|rejected|disabled.',
    ]),
    ep('EP-SC-076', 'SP-06', 'GET', '/channel/reps/{id}', 'channel', 'sc.reps.view', [
        'name' => 'Show rep',
        'name_ar' => 'بطاقة مندوب',
        'r' => [
            'id' => 70,
            'name' => 'أحمد المندوب',
            'phone' => '+963933000070',
            'status' => 'active',
            'zone_ids' => [12],
            'on_duty' => true,
            'max_discount_percent' => 5,
            'max_cash_hold' => 5000000,
        ],
        'd' => 'Foreign channel rep → 404.',
    ]),
    ep('EP-SC-077', 'SP-06', 'POST', '/channel/reps/{id}/approve', 'channel', 'sc.reps.update', [
        'name' => 'Approve rep',
        'name_ar' => 'اعتماد مندوب',
        'b' => ['reason' => 'ملف مكتمل'],
        'r' => ['id' => 70, 'status' => 'active'],
        'd' => 'pending_review → active. reason optional. Illegal transition → 409.',
    ]),
    ep('EP-SC-078', 'SP-06', 'POST', '/channel/reps/{id}/reject', 'channel', 'sc.reps.update', [
        'name' => 'Reject rep',
        'name_ar' => 'رفض مندوب',
        'b' => ['reason' => 'بيانات ناقصة'],
        'r' => ['id' => 70, 'status' => 'rejected'],
        'd' => 'pending_review → rejected. reason required.',
    ]),
    ep('EP-SC-079', 'SP-06', 'POST', '/channel/reps/{id}/disable', 'channel', 'sc.reps.disable', [
        'name' => 'Disable rep',
        'name_ar' => 'تعطيل مندوب',
        'b' => ['reason' => 'ترك العمل'],
        'r' => ['id' => 70, 'status' => 'disabled'],
        'd' => 'active → disabled. reason required.',
        'crit' => true,
    ]),

    ep('EP-SC-080', 'SP-13', 'GET', '/channel/invoices', 'channel', 'sc.finance.view', [
        'name' => 'List invoices',
        'name_ar' => 'الفواتير',
        'q' => listQuery([
            'filter[status]' => 'open',
            'filter[retailer_id]' => '481',
            'filter[rep_id]' => '70',
            'filter[date]' => '2026-03-01',
        ]),
        'r' => [['id' => 501, 'no' => 'INV-501', 'total' => 48000, 'status' => 'open']],
    ]),
    ep('EP-SC-080A', 'SP-13', 'GET', '/channel/invoices/{id}', 'channel', 'sc.finance.view', [
        'name' => 'Invoice detail',
        'name_ar' => 'تفاصيل فاتورة',
        'r' => [
            'id' => 501,
            'no' => 'INV-501',
            'status' => 'open',
            'retailer_id' => 481,
            'rep_id' => 70,
            'total' => 48000,
            'paid_total' => 0,
            'credited_total' => 0,
            'remaining' => 48000,
            'lines' => [['id' => 1, 'product_id' => 880, 'qty' => 4, 'amount' => 48000]],
            'created_at' => '2026-03-01T09:00:00+03:00',
        ],
        'd' => 'lines[].id is the line_id for credit-note. Foreign id → 404.',
    ]),
    ep('EP-SC-081', 'SP-13', 'POST', '/channel/invoices/{id}/credit-note', 'channel', 'sc.finance.credit_note', [
        'name' => 'Issue credit note',
        'name_ar' => 'إشعار دائن',
        'b' => [
            'lines' => [['line_id' => 1, 'qty' => 1, 'amount' => 12000]],
            'reason' => 'فرق تسليم',
        ],
        'r' => ['credit_note_id' => 88, 'no' => 'CN-88'],
        'dual' => true,
        'crit' => true,
    ]),
    ep('EP-SC-082', 'SP-13', 'POST', '/channel/invoices/{id}/void', 'channel', 'sc.finance.void_invoice', [
        'name' => 'Void invoice',
        'name_ar' => 'إلغاء فاتورة',
        'b' => ['reason' => 'إصدار مكرر بعد تعارض مزامنة'],
        'r' => ['status' => 'void'],
        'dual' => true,
        'crit' => true,
    ]),
    ep('EP-SC-083', 'SP-13', 'POST', '/channel/payments', 'channel', 'sc.finance.payment', [
        'name' => 'Record office payment',
        'name_ar' => 'تسجيل دفعة مكتبية',
        'b' => [
            'retailer_id' => 481,
            'amount' => 20000,
            'method' => 'cash',
            'invoice_id' => 501,
        ],
        'r' => ['payment_id' => 301, 'retailer_receivable' => 28000],
        'd' => 'SOD-01: must not be held together with sc.orders.confirm.',
        'e' => [403 => 'sod_violation'],
    ]),
    ep('EP-SC-084', 'SP-13', 'POST', '/channel/reps/{id}/settle', 'channel', 'sc.reps.settle', [
        'name' => 'Settle rep wallet',
        'name_ar' => 'تسوية عهدة المندوب',
        'b' => ['amount' => 1500000, 'operation_no' => 'OP-7781'],
        'r' => ['receipt_pdf_url' => 'https://files.example/settle-70.pdf', 'new_balance' => 250000],
        'd' => 'Invariant: wallet.net_balance == SUM(collected) − SUM(settled) (AC-06).',
    ]),
    ep('EP-SC-085', 'SP-13', 'GET', '/channel/finance/aging', 'channel', 'sc.finance.aging', [
        'name' => 'Receivables aging',
        'name_ar' => 'أعمار الذمم',
        'q' => ['group_by' => 'zone'],
        'r' => [
            'group_by' => 'zone',
            'buckets' => ['0_30' => 12000000, '31_60' => 4000000, '61_90' => 1500000, 'over_90' => 200000],
            'groups' => [['key' => 12, 'label' => null, 'buckets' => ['0_30' => 8000000, '31_60' => 0, '61_90' => 0, 'over_90' => 0]]],
        ],
        'd' => 'group_by: zone|rep. buckets are channel totals; groups split by zone_id or rep_id.',
    ]),
    ep('EP-SC-086', 'SP-13', 'PUT', '/channel/retailers/{id}/credit', 'channel', 'sc.retailers.credit', [
        'name' => 'Retailer credit limit',
        'name_ar' => 'سقف ائتمان التاجر',
        'b' => [
            'credit_limit' => 500000,
            'grace_days' => 7,
            'on_exceed' => 'block',
        ],
        'r' => ['retailer_id' => 481, 'credit_limit' => 500000, 'on_exceed' => 'block'],
        'd' => 'on_exceed: warn|block|manual_approval. manual_approval is stored but behaves as block until a credit-approval queue EP exists — confirm returns 423 credit_limit_exceeded for both block and manual_approval. warn never blocks.',
    ]),
    ep('EP-SC-087', 'SP-13', 'GET', '/channel/reps/{id}/wallet', 'channel', 'sc.reps.wallet', [
        'name' => 'Rep wallet (channel read)',
        'name_ar' => 'محفظة المندوب',
        'r' => [
            'net_balance' => 250000,
            'stats' => ['invoices_delivered' => 12, 'collected_total' => 1750000, 'receivables' => 48000],
            'today' => ['invoices' => 2, 'collected' => 90000, 'receivables' => 12000],
        ],
        'd' => 'Same ledger math as GET /app/rep/wallet. Foreign channel → 404.',
        'crit' => true,
    ]),
    ep('EP-SC-088', 'SP-06', 'GET', '/channel/rep-zone-requests', 'channel', 'sc.reps.view', [
        'name' => 'List rep zone requests',
        'name_ar' => 'طلبات مناطق المندوبين',
        'q' => listQuery(['filter[status]' => 'pending_approval']),
        'r' => [[
            'id' => 1,
            'rep_user_id' => 70,
            'zone_id' => 12,
            'note' => 'تغطية جديدة',
            'status' => 'pending_approval',
        ]],
    ]),
    ep('EP-SC-089', 'SP-06', 'POST', '/channel/rep-zone-requests/{id}/decide', 'channel', 'sc.reps.update', [
        'name' => 'Decide rep zone request',
        'name_ar' => 'قرار طلب منطقة مندوب',
        'b' => ['decision' => 'approve', 'reason' => 'ضمن التغطية'],
        'r' => ['id' => 1, 'status' => 'approved'],
        'd' => 'decision: approve|reject. Approve attaches zone to RepProfileZone.',
    ]),
    ep('EP-SC-093A', 'SP-06', 'GET', '/channel/rep-sourced-shops', 'channel', 'sc.reps.view', [
        'name' => 'List rep-sourced shops',
        'name_ar' => 'محلات سجّلها المندوب',
        'q' => listQuery(['filter[status]' => 'pending_sync']),
        'r' => [[
            'id' => 490,
            'rep_user_id' => 70,
            'shop_name' => 'ميني ماركت الشام',
            'phone' => '+963988000000',
            'zone_id' => 12,
            'status' => 'pending_sync',
            'retailer_id' => 481,
        ]],
    ]),
    ep('EP-SC-093B', 'SP-06', 'POST', '/channel/rep-sourced-shops/{id}/decide', 'channel', 'sc.reps.update', [
        'name' => 'Decide rep-sourced shop',
        'name_ar' => 'قرار محل مندوب',
        'b' => ['decision' => 'approve', 'reason' => 'تحقق ميداني'],
        'r' => ['id' => 490, 'status' => 'linked'],
        'd' => 'decision: approve|reject. Approve activates RetailerProfile and marks shop linked.',
    ]),

    ep('EP-SC-090', 'SP-14', 'POST', '/channel/notifications', 'channel', 'sc.notify.send', [
        'name' => 'Send notification',
        'name_ar' => 'إرسال إشعار',
        'b' => [
            'title' => 'عرض جديد',
            'body' => 'اشترِ 10 واحصل على 1',
            'icon' => 'offer',
            'image' => 'media_id_9',
            'action' => ['type' => 'offer', 'target' => 44],
            'targeting' => ['type' => 'zone', 'ids' => [12]],
            'channels' => ['push', 'in_app'],
            'scheduled_at' => null,
        ],
        'r' => ['id' => 800, 'status' => 'queued'],
    ]),
    ep('EP-SC-091A', 'SP-14', 'GET', '/channel/notifications/templates', 'channel', 'sc.notify.templates', [
        'name' => 'List notification templates',
        'name_ar' => 'قوالب الإشعارات',
        'r' => [['event_key' => 'order.confirmed', 'title' => 'تم تأكيد طلبك', 'enabled' => true, 'channels' => ['push']]],
    ]),
    ep('EP-SC-091B', 'SP-14', 'PUT', '/channel/notifications/templates', 'channel', 'sc.notify.templates', [
        'name' => 'Upsert notification template',
        'name_ar' => 'تحديث قالب إشعار',
        'b' => [
            'event_key' => 'order.confirmed',
            'title' => 'تم تأكيد طلبك',
            'body' => 'الطلب {{sub_order_no}} قيد التجهيز',
            'enabled' => true,
            'channels' => ['push', 'in_app'],
        ],
        'r' => ['event_key' => 'order.confirmed'],
    ]),
    ep('EP-SC-092', 'SP-14', 'GET', '/channel/notifications/log', 'channel', 'sc.notify.view', [
        'name' => 'Notification log',
        'name_ar' => 'سجل الإشعارات',
        'q' => listQuery(),
        'r' => [['at' => '2026-03-01T09:12:00+03:00', 'recipient' => 481, 'template' => 'order.confirmed', 'status' => 'sent', 'failure_reason' => null]],
    ]),

    ep('EP-SC-100A', 'SP-15', 'GET', '/channel/content/intro', 'channel', 'sc.content.intro', [
        'name' => 'Get intro screen',
        'name_ar' => 'شاشة الانترو',
        'r' => [
            'enabled' => true,
            'text' => 'مرحباً بتجار دمشق',
            'media_type' => 'video',
            'media_id' => 'media_intro',
            'duration' => 8,
            'targeting' => ['activity_type_ids' => [3], 'zone_ids' => [12]],
        ],
    ]),
    ep('EP-SC-100B', 'SP-15', 'PUT', '/channel/content/intro', 'channel', 'sc.content.intro', [
        'name' => 'Update intro screen',
        'name_ar' => 'تحديث الانترو',
        'b' => [
            'enabled' => true,
            'text' => 'مرحباً بتجار دمشق',
            'media_type' => 'video',
            'media_id' => 'media_intro',
            'duration' => 8,
            'targeting' => ['activity_type_ids' => [3], 'zone_ids' => [12]],
        ],
        'r' => ['enabled' => true],
    ]),
    ep('EP-SC-101A', 'SP-15', 'GET', '/channel/content/banners', 'channel', 'sc.content.banners', [
        'name' => 'List banners',
        'name_ar' => 'البنرات',
        'q' => listQuery(),
        'r' => [['id' => 9, 'media_type' => 'image', 'placements' => ['home_top']]],
    ]),
    ep('EP-SC-101B', 'SP-15', 'POST', '/channel/content/banners', 'channel', 'sc.content.banners', [
        'name' => 'Create banner',
        'name_ar' => 'إنشاء بنر',
        'b' => [
            'media_type' => 'image',
            'media_id' => 'media_banner_2',
            'link' => ['type' => 'offer', 'target' => 44],
            'placements' => ['home_top'],
            'targeting' => ['activity_type_ids' => [3], 'zone_ids' => [12]],
            'starts_at' => '2026-03-01T00:00:00+03:00',
            'ends_at' => '2026-03-31T23:59:59+03:00',
            'order' => 1,
            'weight' => 10,
        ],
        'r' => ['id' => 9],
    ]),
    ep('EP-SC-101C', 'SP-15', 'PUT', '/channel/content/banners/{id}', 'channel', 'sc.content.banners', [
        'name' => 'Update banner',
        'name_ar' => 'تعديل بنر',
        'b' => [
            'media_type' => 'image',
            'media_id' => '42',
            'link' => ['type' => 'offer', 'target' => 44],
            'placements' => ['home_top'],
            'targeting' => ['activity_type_ids' => [3], 'zone_ids' => [12]],
            'starts_at' => '2026-03-01T00:00:00+03:00',
            'ends_at' => '2026-03-31T23:59:59+03:00',
            'order' => 1,
            'weight' => 10,
        ],
        'r' => ['id' => 9],
        'e' => [404 => 'not_found'],
    ]),
    ep('EP-SC-101D', 'SP-15', 'DELETE', '/channel/content/banners/{id}', 'channel', 'sc.content.banners', [
        'name' => 'Delete banner',
        'name_ar' => 'حذف بنر',
        'r' => ['deleted' => true],
        'e' => [404 => 'not_found'],
    ]),
    ep('EP-SC-102', 'SP-15', 'GET', '/channel/content/banners/{id}/stats', 'channel', 'sc.content.banners', [
        'name' => 'Banner stats',
        'name_ar' => 'إحصاء البنر',
        'r' => ['impressions' => 12000, 'clicks' => 840, 'ctr' => 700],
        'd' => 'ctr is integer basis points at scale 10^4 (840/12000 = 700), never a float.',
    ]),
    ep('EP-SC-103A', 'SP-15', 'GET', '/channel/content/sliders', 'channel', 'sc.content.sliders', [
        'name' => 'List sliders',
        'name_ar' => 'الساليدرات',
        'r' => [['id' => 4, 'name' => 'الأكثر مبيعاً', 'source' => 'algorithm', 'algorithm' => 'best_selling']],
    ]),
    ep('EP-SC-103B', 'SP-15', 'POST', '/channel/content/sliders', 'channel', 'sc.content.sliders', [
        'name' => 'Create slider',
        'name_ar' => 'إنشاء ساليدر',
        'b' => [
            'name' => 'الأكثر مبيعاً',
            'source' => 'algorithm',
            'source_ref' => null,
            'algorithm' => 'best_selling',
            'placements' => ['home'],
            'items_count' => 12,
            'show_all_button' => true,
            'targeting' => ['activity_type_ids' => [3]],
        ],
        'r' => ['id' => 4],
        'd' => 'source: manual|brand|category|offers|algorithm. algorithm: new_arrivals|best_selling|most_ordered_by_retailer|suggested|similar|same_brand.',
    ]),
    ep('EP-SC-103C', 'SP-15', 'PUT', '/channel/content/sliders/{id}', 'channel', 'sc.content.sliders', [
        'name' => 'Update slider',
        'name_ar' => 'تعديل ساليدر',
        'b' => [
            'name' => 'الأكثر مبيعاً',
            'source' => 'algorithm',
            'source_ref' => null,
            'algorithm' => 'best_selling',
            'placements' => ['home'],
            'items_count' => 12,
            'show_all_button' => true,
            'targeting' => ['activity_type_ids' => [3]],
        ],
        'r' => ['id' => 4],
        'e' => [404 => 'not_found'],
    ]),
    ep('EP-SC-103D', 'SP-15', 'DELETE', '/channel/content/sliders/{id}', 'channel', 'sc.content.sliders', [
        'name' => 'Delete slider',
        'name_ar' => 'حذف ساليدر',
        'r' => ['deleted' => true],
        'e' => [404 => 'not_found'],
    ]),

    ep('EP-SC-110A', 'SP-15', 'GET', '/channel/loyalty/rules', 'channel', 'sc.loyalty.manage', [
        'name' => 'Loyalty rules',
        'name_ar' => 'قواعد النقاط',
        'r' => [
            'retailer_rules' => [['event' => 'invoice_paid', 'points_per_1000' => 1]],
            'rep_rules' => [['event' => 'delivery_completed', 'points' => 5]],
            'tiers' => [['name' => 'silver', 'threshold' => 1000, 'benefits' => ['priority_support']]],
        ],
    ]),
    ep('EP-SC-110B', 'SP-15', 'PUT', '/channel/loyalty/rules', 'channel', 'sc.loyalty.manage', [
        'name' => 'Update loyalty rules',
        'name_ar' => 'تحديث قواعد النقاط',
        'b' => [
            'retailer_rules' => [['event' => 'invoice_paid', 'points_per_1000' => 1]],
            'rep_rules' => [['event' => 'delivery_completed', 'points' => 5]],
            'tiers' => [
                ['name' => 'bronze', 'threshold' => 0, 'benefits' => []],
                ['name' => 'silver', 'threshold' => 1000, 'benefits' => ['priority_support']],
                ['name' => 'gold', 'threshold' => 5000, 'benefits' => ['extra_offer']],
            ],
        ],
        'r' => ['updated' => true],
    ]),
    ep('EP-SC-111A', 'SP-15', 'GET', '/channel/loyalty/rewards', 'channel', 'sc.loyalty.manage', [
        'name' => 'List rewards',
        'name_ar' => 'المكافآت',
        'q' => listQuery(),
        'r' => [['id' => 3, 'name' => 'كرتون زيت', 'points_cost' => 2000, 'stock' => 40]],
    ]),
    ep('EP-SC-111B', 'SP-15', 'POST', '/channel/loyalty/rewards', 'channel', 'sc.loyalty.manage', [
        'name' => 'Create reward',
        'name_ar' => 'إنشاء مكافأة',
        'b' => ['name' => 'كرتون زيت', 'points_cost' => 2000, 'stock' => 40, 'expires_at' => '2026-12-31'],
        'r' => ['id' => 3],
    ]),
    ep('EP-SC-111C', 'SP-15', 'PUT', '/channel/loyalty/rewards/{id}', 'channel', 'sc.loyalty.manage', [
        'name' => 'Update reward',
        'name_ar' => 'تعديل مكافأة',
        'b' => ['name' => 'كرتون زيت', 'points_cost' => 1800, 'stock' => 35, 'expires_at' => '2026-12-31'],
        'r' => ['id' => 3],
        'e' => [404 => 'not_found', 409 => 'illegal_transition'],
        'd' => 'Stopped rewards → 409.',
    ]),
    ep('EP-SC-111D', 'SP-15', 'PATCH', '/channel/loyalty/rewards/{id}/stop', 'channel', 'sc.loyalty.manage', [
        'name' => 'Stop reward',
        'name_ar' => 'إيقاف مكافأة',
        'b' => ['reason' => 'نفاد المخزون'],
        'r' => ['status' => 'stopped'],
        'e' => [404 => 'not_found', 409 => 'illegal_transition'],
    ]),

    ep('EP-SC-120', 'SP-16', 'GET', '/channel/dashboard', 'channel', 'sc.dashboard.view', [
        'name' => 'Channel dashboard',
        'name_ar' => 'لوحة القناة',
        'r' => [
            'kpis' => [
                'sales' => 62000000,
                'orders_by_status' => ['pending' => 12, 'confirmed' => 40, 'on_the_way' => 9],
                'cash_collected' => 18000000,
                'receivables' => ['total' => 42000000, 'overdue' => 6000000],
                'retailers' => ['active' => 420, 'registered' => 510, 'new' => 14],
                'avg_order_value' => 38000,
                'avg_confirm_time' => 11,
                'avg_delivery_time' => 140,
                'fill_rate' => 0.97,
            ],
            'alerts' => [['type' => 'waiting_orders', 'count' => 8, 'action_url' => '/orders?filter[waiting_over_minutes]=30']],
            'charts' => [
                'daily_sales' => [],
                'by_zone' => [],
                'top_products' => [],
                'top_retailers' => [],
                'rep_performance' => [],
                'heatmap' => [],
            ],
        ],
    ]),
    ep('EP-SC-121', 'SP-16', 'GET', '/channel/reports/{type}', 'channel', 'sc.reports.view', [
        'name' => 'Channel report',
        'name_ar' => 'تقرير القناة',
        'q' => ['date_from' => '2026-02-01', 'date_to' => '2026-02-28', 'filter[zone_id]' => '12'],
        'r' => ['type' => 'sales', 'rows' => [], 'totals' => []],
        'd' => 'type ∈ sales|products|retailers|reps|zones|inventory|finance|offers|operations',
    ]),
    ep('EP-SC-122', 'SP-16', 'POST', '/channel/reports/{type}/export', 'channel', 'sc.reports.export', [
        'name' => 'Export report',
        'name_ar' => 'تصدير تقرير',
        'b' => ['format' => 'xlsx', 'filters' => ['zone_id' => 12, 'date_from' => '2026-02-01', 'date_to' => '2026-02-28']],
        'r' => ['job_id' => 'job_rep_exp_1'],
    ]),
    ep('EP-SC-123', 'SP-16', 'GET', '/channel/reports/margins', 'channel', 'sc.reports.margins', [
        'name' => 'Margin report',
        'name_ar' => 'تقرير الهوامش',
        'q' => ['date_from' => '2026-02-01', 'date_to' => '2026-02-28'],
        'r' => ['by_product' => [], 'by_zone' => []],
        'crit' => true,
    ]),
    ep('EP-SC-124', 'SP-16', 'GET', '/channel/jobs/{id}', 'channel', 'sc.reports.view', [
        'name' => 'Job status',
        'name_ar' => 'حالة مهمة',
        'r' => [
            'id' => 'job_rep_exp_1',
            'type' => 'report_export',
            'status' => 'done',
            'progress' => 100,
            'result' => ['download_url' => 'https://cdn.example/exports/rep.xlsx'],
            'error' => null,
            'created_at' => '2026-03-01T09:00:00+03:00',
            'finished_at' => '2026-03-01T09:00:12+03:00',
        ],
        'e' => [404 => 'not_found'],
        'd' => 'type ∈ catalog_export|catalog_import|report_export|price_list_schedule. status ∈ queued|running|done|failed. progress 0–100. Channel-scoped; foreign job → 404.',
    ]),

    // Previously live outside the catalog (status "حيّ خارج الكتالوج"). Contract commit.
    ep('EP-SC-130A', 'SP-15', 'GET', '/channel', 'channel', 'sc.settings.view', [
        'name' => 'Own channel settings',
        'name_ar' => 'إعدادات القناة',
        'r' => [
            'id' => 1,
            'name' => 'شركة النور',
            'slug' => 'alnoor',
            'legal_name' => 'شركة النور للتجارة',
            'tax_number' => '123456789',
            'phone' => '+963911000001',
            'email' => 'ops@alnoor.example',
            'status' => 'active',
            'allowed_next' => ['suspended', 'archived'],
            'settings' => new stdClass(),
            'created_at' => '2026-01-01T00:00:00+03:00',
        ],
        'd' => 'The authenticated channel tenant reading itself. No X-Channel-Id.',
    ]),
    ep('EP-SC-130B', 'SP-15', 'PUT', '/channel', 'channel', 'sc.settings.update', [
        'name' => 'Update own channel settings',
        'name_ar' => 'تحديث إعدادات القناة',
        'b' => [
            'name' => 'شركة النور',
            'legal_name' => 'شركة النور للتجارة',
            'tax_number' => '123456789',
            'phone' => '+963911000001',
            'email' => 'ops@alnoor.example',
            'settings' => [
                'locale' => 'ar',
                'quiet_hours' => ['start' => '22:00', 'end' => '08:00', 'timezone' => 'Asia/Damascus'],
                'returns_sla_hours' => 24,
            ],
        ],
        'r' => [
            'id' => 1,
            'name' => 'شركة النور',
            'slug' => 'alnoor',
            'legal_name' => 'شركة النور للتجارة',
            'tax_number' => '123456789',
            'phone' => '+963911000001',
            'email' => 'ops@alnoor.example',
            'status' => 'active',
            'allowed_next' => ['suspended', 'archived'],
            'settings' => [
                'locale' => 'ar',
                'quiet_hours' => ['start' => '22:00', 'end' => '08:00', 'timezone' => 'Asia/Damascus'],
                'returns_sla_hours' => 24,
            ],
            'created_at' => '2026-01-01T00:00:00+03:00',
        ],
        'd' => 'Partial update. status is not writable here — lifecycle stays on the platform. settings.quiet_hours {start,end,timezone} defers push/whatsapp delivery; settings.returns_sla_hours (int, default 24) sets return_requests.sla_due_at on create.',
    ]),
    ep('EP-SC-131A', 'SP-03', 'GET', '/channel/zones', 'channel', 'sc.zones.view', [
        'name' => 'Channel coverage zones',
        'name_ar' => 'مناطق تغطية القناة',
        'r' => [[
            'id' => 1,
            'zone_id' => 12,
            'zone_name' => 'المزة',
            'delivery_days' => ['sun', 'tue', 'thu'],
            'delivery_fee' => '50000.00',
            'min_order_value' => '100000.00',
        ]],
        'd' => 'Unpaginated. delivery_fee and min_order_value are decimal strings (unique money exception on this guard).',
    ]),
    ep('EP-SC-131B', 'SP-03', 'POST', '/channel/zones', 'channel', 'sc.zones.manage', [
        'name' => 'Upsert coverage zone',
        'name_ar' => 'إضافة/تحديث تغطية منطقة',
        'b' => [
            'zone_id' => 12,
            'delivery_days' => ['sun', 'tue', 'thu'],
            'delivery_windows' => [['day' => 'sun', 'start' => '09:00', 'end' => '17:00']],
            'delivery_fee' => '50000.00',
            'min_order_value' => '100000.00',
        ],
        'r' => [
            'id' => 1,
            'zone_id' => 12,
            'zone_name' => 'المزة',
            'delivery_days' => ['sun', 'tue', 'thu'],
            'delivery_fee' => '50000.00',
            'min_order_value' => '100000.00',
        ],
        'd' => 'updateOrCreate on zone_id within the tenant. Optional delivery_windows: array of {day ∈ sun…sat, start/end H:i}.',
    ]),
    ep('EP-SC-131C', 'SP-03', 'DELETE', '/channel/zones/{id}', 'channel', 'sc.zones.manage', [
        'name' => 'Remove coverage zone',
        'name_ar' => 'حذف تغطية منطقة',
        'r' => null,
        'd' => '204 empty body. Path param is the coverage row id (channel_zone.id), not zone_id.',
    ]),

    ep('EP-SC-140', 'SP-13', 'GET', '/channel/retailers', 'channel', 'sc.retailers.view', [
        'name' => 'List retailers in coverage',
        'name_ar' => 'تجّار التغطية',
        'q' => listQuery(['filter[zone_id]' => '12', 'search' => 'نور']),
        'r' => [[
            'id' => 481,
            'shop_name' => 'بقالية النور',
            'phone' => '+963931000002',
            'zone_id' => 12,
            'status' => 'active',
        ]],
        'd' => 'Retailers whose zone is in this channel coverage. Id is retailer_profile id for credit/payments.',
    ]),
    ep('EP-SC-164', 'SP-13', 'GET', '/channel/retailers/{id}', 'channel', 'sc.retailers.view', [
        'name' => 'Retailer 360 (rich)',
        'name_ar' => 'بطاقة التاجر الموسّعة',
        'r' => [
            'id' => 481,
            'shop_name' => 'بقالية النور',
            'phone' => '+963931000002',
            'zone_id' => 12,
            'activity_type_id' => 3,
            'status' => 'active',
            'credit' => ['credit_limit' => 500000, 'grace_days' => 7, 'on_exceed' => 'block'],
            'outstanding' => 120000,
            'groups' => [['id' => 1, 'name' => 'VIP']],
            'assigned_rep_ids' => [70],
            'last_order_at' => '2026-09-20T10:00:00+03:00',
            'recent_orders' => [['id' => 9001, 'sub_order_no' => 'SO-9001', 'status' => 'delivered', 'total' => 120000]],
            'top_products' => [['product_id' => 880, 'name' => 'زيت', 'qty' => 40]],
        ],
        'e' => [404 => 'not_found'],
        'd' => 'Same handler as EP-SC-140A; richer fields (outstanding, groups, assigned_rep_ids, last_order_at). Duplicate path for status tracking — OpenAPI operationId is EP-SC-164 (later code wins).',
    ]),
    ep('EP-SC-140A', 'SP-13', 'GET', '/channel/retailers/{id}', 'channel', 'sc.retailers.view', [
        'name' => 'Retailer 360',
        'name_ar' => 'ملف التاجر',
        'r' => [
            'id' => 481,
            'shop_name' => 'بقالية النور',
            'phone' => '+963931000002',
            'zone_id' => 12,
            'activity_type_id' => 3,
            'status' => 'active',
            'credit' => ['credit_limit' => 500000, 'grace_days' => 7, 'on_exceed' => 'block'],
            'outstanding' => 120000,
            'groups' => [['id' => 1, 'name' => 'VIP']],
            'assigned_rep_ids' => [70],
            'last_order_at' => '2026-09-20T10:00:00+03:00',
            'recent_orders' => [['id' => 9001, 'sub_order_no' => 'SO-9001', 'status' => 'delivered', 'total' => 120000]],
            'top_products' => [['product_id' => 880, 'name' => 'زيت', 'qty' => 40]],
        ],
        'e' => [404 => 'not_found'],
        'd' => 'Coverage-scoped. Foreign or out-of-coverage id → 404. credit/outstanding from finance; groups + assigned_rep_ids from identity; recent_orders/top_products/last_order_at via ordering contract. Richer fields also tracked as EP-SC-164 on this same path.',
    ]),
    ep('EP-SC-075A', 'SP-06', 'GET', '/channel/reps/{id}/live', 'channel', 'sc.reps.view', [
        'name' => 'Rep live location',
        'name_ar' => 'موقع المندوب الحي',
        'r' => ['lat' => 33.51, 'lng' => 36.29, 'at' => '2026-03-01T10:00:00+03:00', 'on_duty' => true],
        'e' => [404 => 'not_found'],
        'd' => 'Latest RepLocationPing for a rep on this channel. No ping → lat/lng/at null, on_duty still reported.',
    ]),
    ep('EP-SC-131D', 'SP-03', 'GET', '/channel/zones/coverage', 'channel', 'sc.zones.view', [
        'name' => 'Zone coverage gaps',
        'name_ar' => 'فجوات تغطية المناطق',
        'r' => [
            'without_reps' => [15],
            'without_warehouse' => [],
        ],
        'd' => 'Channel coverage zones with zero active reps, and zones with no default warehouse for the channel (all coverage zones when default warehouse is missing).',
    ]),
    ep('EP-SC-150A', 'SP-15', 'GET', '/channel/users', 'channel', 'sc.iam.users_view', [
        'name' => 'List channel users',
        'name_ar' => 'مستخدمو القناة',
        'r' => [[
            'id' => 1,
            'name' => 'محمد',
            'phone' => '+963911000001',
            'role' => 'channel_manager',
            'status' => 'active',
            'last_login_at' => null,
        ]],
        'd' => 'Memberships for the current tenant. DOC-08 sc.iam.users_view.',
    ]),
    ep('EP-SC-150B', 'SP-15', 'POST', '/channel/users/invite', 'channel', 'sc.iam.users_manage', [
        'name' => 'Invite channel user',
        'name_ar' => 'دعوة مستخدم قناة',
        'b' => ['name' => 'سارة', 'phone' => '+963933000001', 'invite_via' => 'sms'],
        'r' => ['invite_id' => 12, 'expires_at' => '2026-03-04T10:00:00+03:00'],
        'd' => 'Creates/updates ChannelUser, membership, and a 72h ChannelManagerInvite. DOC-08 sc.iam.users_manage.',
    ]),
    ep('EP-SC-142A', 'SP-13', 'GET', '/channel/retailer-groups', 'channel', 'sc.retailers.groups', [
        'name' => 'List retailer groups',
        'name_ar' => 'مجموعات التجار',
        'q' => listQuery(['filter[search]' => 'VIP']),
        'r' => [['id' => 3, 'name' => 'VIP المزة', 'retailer_ids' => [481, 482], 'members_count' => 2]],
        'd' => 'Channel-owned groups for price lists (type=group) and offer targeting (scope=groups).',
    ]),
    ep('EP-SC-142B', 'SP-13', 'POST', '/channel/retailer-groups', 'channel', 'sc.retailers.groups', [
        'name' => 'Create retailer group',
        'name_ar' => 'إنشاء مجموعة تجار',
        'b' => ['name' => 'VIP المزة', 'retailer_ids' => [481, 482]],
        'r' => ['id' => 3],
        'd' => 'retailer_ids must be retailer_profile ids in this channel coverage. Empty membership allowed.',
    ]),
    ep('EP-SC-142C', 'SP-13', 'PUT', '/channel/retailer-groups/{id}', 'channel', 'sc.retailers.groups', [
        'name' => 'Update retailer group',
        'name_ar' => 'تعديل مجموعة تجار',
        'b' => ['name' => 'VIP المزة', 'retailer_ids' => [481]],
        'r' => ['id' => 3],
        'd' => 'Replaces name and membership atomically.',
    ]),
    ep('EP-SC-142D', 'SP-13', 'DELETE', '/channel/retailer-groups/{id}', 'channel', 'sc.retailers.groups', [
        'name' => 'Delete retailer group',
        'name_ar' => 'حذف مجموعة تجار',
        'r' => ['deleted' => true],
        'd' => '422 ref_in_use when a price list or offer still targets the group.',
    ]),
    ep('EP-SC-141', 'SP-09', 'GET', '/channel/warehouses', 'channel', 'sc.inventory.view', [
        'name' => 'List channel warehouses',
        'name_ar' => 'مستودعات القناة',
        'r' => [['id' => 1, 'name' => 'مستودع المزة', 'status' => 'active']],
        'd' => 'Unpaginated picker for inventory adjust/transfer. No create on this path.',
    ]),
    ep('EP-SC-160', 'SP-06', 'GET', '/channel/reps/live', 'channel', 'sc.reps.track', [
        'name' => 'Live map of on-duty reps',
        'name_ar' => 'خريطة المندوبين المباشرين',
        'r' => [['rep_id' => 70, 'name' => 'أحمد', 'zone_ids' => [12], 'lat' => 33.51, 'lng' => 36.29, 'at' => '2026-09-24T12:00:00+03:00', 'on_duty' => true]],
        'd' => 'On-duty reps for the tenant. lat/lng/at null when no ping. Single-rep live remains GET /channel/reps/{id}/live.',
    ]),

    ep('EP-SC-161', 'SP-03', 'GET', '/channel/delivery-calendar', 'channel', 'sc.zones.view', [
        'name' => 'Weekly delivery calendar',
        'name_ar' => 'تقويم التوصيل الأسبوعي',
        'q' => ['week' => '2026-09-21'],
        'r' => ['week_start' => '2026-09-20', 'days' => [['date' => '2026-09-20', 'weekday' => 'sun', 'zones' => [['zone_id' => 12, 'zone_name' => 'المزة']]]]],
        'd' => 'Derived from channel_zone.delivery_days. week= any date in the week (Asia/Damascus); week_start is Sunday. No new table.',
    ]),

    ep('EP-SC-163', 'SP-03', 'GET', '/channel/zones/map', 'channel', 'sc.zones.view', [
        'name' => 'Zone map with polygons',
        'name_ar' => 'خريطة المناطق بالمضلعات',
        'r' => [['zone_id' => 12, 'zone_name' => 'المزة', 'polygon' => null, 'delivery_days' => ['sun', 'wed'], 'delivery_windows' => [['day' => 'sun', 'start' => '09:00', 'end' => '17:00']]]],
        'd' => 'Joins channel_zone coverage with reference zones.polygon. delivery_windows from channel_zone JSON.',
    ]),
];
