<?php

declare(strict_types=1);

$cart = [
    'sections' => [[
        'supply_channel_ref' => 'ch_a1',
        'temp_order_no' => 'T-481-03',
        'note' => null,
        'lines' => [[
            'id' => 11,
            'product_id' => 880,
            'name' => 'زيت دوار الشمس 1 لتر',
            'qty' => 4,
            'unit_price' => 12000,
            'line_total' => 48000,
        ]],
        'subtotal' => 48000,
        'discount' => 0,
        'total' => 48000,
    ]],
    'summary' => [
        'grand_total' => 48000,
        'total_discount' => 0,
        'final_total' => 48000,
        'estimated_delivery' => '2026-03-02',
    ],
    'applied_offers' => [],
];

$productCard = [
    'id' => 880,
    'name' => 'زيت دوار الشمس 1 لتر',
    'brand' => ['id' => 12, 'name' => 'نور'],
    'image' => 'https://cdn.example/p/880.jpg',
    'sale_unit' => 'قطعة',
    'min_order_qty' => 1,
    'price' => ['type' => 'tiered', 'value' => 12000, 'from' => 11000, 'to' => 12000, 'label' => 'السعر حسب الكمية'],
    'discount' => 0,
    'price_after' => 12000,
    'sold_count' => 420,
    'availability' => 'in_stock',
    'lead_time_days' => 2,
    'rating' => 4.6,
    'is_favorite' => false,
    'has_offer' => true,
    'variants_count' => 2,
];

return [
    ep('EP-RT-001', 'SP-01', 'POST', '/app/retailer/register', 'retailer', null, [
        'name' => 'Complete retailer registration',
        'name_ar' => 'إكمال تسجيل التاجر',
        'b' => [
            'owner_name' => 'أبو خالد',
            'shop_name' => 'بقالية النور',
            'activity_type_id' => 3,
            'category_ids' => [10, 11],
            'equipment_ids' => [1],
            'governorate_id' => 1,
            'zone_id' => 12,
            'lat' => 33.5031,
            'lng' => 36.2765,
            'address' => 'المزة فيلات شرقية',
        ],
        'r' => [
            'retailer' => [
                'id' => 481,
                'shop_name' => 'بقالية النور',
                'zone' => ['id' => 12, 'name' => 'المزة'],
                'activity_type' => ['id' => 3, 'name' => 'بقالة'],
                'status' => 'pending_review',
            ],
            'token' => '40|retailer_xxxxx',
        ],
        'd' => 'No email field ever (REQ-RT-003). Zone must belong to governorate.',
    ]),

    ep('EP-RT-010', 'SP-06', 'GET', '/app/retailer/home', 'retailer', null, [
        'name' => 'Retailer home',
        'name_ar' => 'الرئيسية',
        'r' => [
            'header' => [
                'shop_name' => 'بقالية النور',
                'zone' => ['id' => 12, 'name' => 'المزة'],
                'points' => 1240,
                'tier' => 'silver',
                'unread_notifications' => 3,
                'pending_sync' => 0,
            ],
            'banner' => ['id' => 9, 'image' => 'https://cdn.example/b/9.jpg'],
            'quick_actions' => [
                ['key' => 'orders', 'count' => 2],
                ['key' => 'cart', 'count' => 4],
                ['key' => 'debts', 'count' => 1],
            ],
            'stats' => ['orders_count' => 18, 'total_debt' => 48000, 'delivering_today' => 1],
            'categories' => [['id' => 10, 'name' => 'مواد غذائية', 'image' => null]],
            'offers_slider' => [],
            'brands_slider' => [],
            'dynamic_sliders' => [],
        ],
        'd' => 'Single round-trip for the header (TB-RT-020). No five calls.',
    ]),
    ep('EP-RT-011', 'SP-06', 'GET', '/app/retailer/categories', 'retailer', null, [
        'name' => 'Categories',
        'name_ar' => 'الفئات',
        'q' => ['parent_id' => '10', 'level' => '2'],
        'r' => [['id' => 340, 'name' => 'زيوت', 'image' => null, 'children_count' => 2, 'products_count' => 40]],
        'd' => 'Filtered by the retailer activity type and selected categories.',
    ]),
    ep('EP-RT-012', 'SP-06', 'GET', '/app/retailer/products', 'retailer', null, [
        'name' => 'Browse products',
        'name_ar' => 'المنتجات',
        'q' => listQuery([
            'search' => 'زيت',
            'filter[category_id]' => '340',
            'filter[brand_id]' => '12',
            'filter[offer_only]' => '0',
            'filter[available_only]' => '1',
            'barcode' => '',
        ]),
        'r' => [$productCard],
        'd' => 'availability is in_stock|low|out_of_stock — never a stock number (REQ-IN-06, BR-02, BR-14). price.label is server-composed.',
    ]),
    ep('EP-RT-013', 'SP-06', 'GET', '/app/retailer/products/{id}', 'retailer', null, [
        'name' => 'Product detail',
        'name_ar' => 'تفاصيل منتج',
        'r' => $productCard + [
            'images' => ['https://cdn.example/p/880.jpg'],
            'model_no' => 'SUN-1000',
            'long_description' => '<p>زيت دوار الشمس</p>',
            'specs' => [['key' => 'الحجم', 'value' => '1 لتر']],
            'variants' => [['id' => 1, 'combination' => ['الحجم' => '1L'], 'price' => 12000, 'availability' => 'in_stock', 'barcode' => '6291000000000']],
            'sliders' => [
                'price_comparison' => [],
                'same_brand' => [],
                'similar' => [],
                'suggested' => [],
            ],
        ],
        'd' => 'supply_channel is omitted while related orders are pending (REQ-IN-06).',
    ]),
    ep('EP-RT-014', 'SP-06', 'POST', '/app/retailer/products/{id}/favorite', 'retailer', null, [
        'name' => 'Toggle favorite',
        'name_ar' => 'مفضلة',
        'b' => new stdClass(),
        'r' => ['is_favorite' => true],
    ]),
    ep('EP-RT-015A', 'SP-06', 'GET', '/app/retailer/brands', 'retailer', null, [
        'name' => 'List brands',
        'name_ar' => 'العلامات',
        'q' => listQuery(['filter[activity_type_id]' => '3']),
        'r' => [['id' => 12, 'name' => 'نور', 'logo' => null, 'banner' => null]],
    ]),
    ep('EP-RT-015B', 'SP-06', 'GET', '/app/retailer/brands/{id}', 'retailer', null, [
        'name' => 'Brand page',
        'name_ar' => 'صفحة العلامة',
        'r' => [
            'banner' => null,
            'logo' => null,
            'name' => 'نور',
            'activities' => [['id' => 3, 'name' => 'بقالة']],
            'description' => 'منتجات غذائية',
            'categories' => [['id' => 340, 'name' => 'زيوت']],
            'sliders' => [['key' => 'best_selling', 'items' => []]],
        ],
    ]),

    ep('EP-RT-020', 'SP-09', 'GET', '/app/retailer/cart', 'retailer', null, [
        'name' => 'Get cart',
        'name_ar' => 'السلة',
        'r' => $cart,
        'd' => 'supply_channel_ref is anonymous (ch_a1) until submit (REQ-IN-06 / TB-RT-050).',
        'in' => 'REQ-IN-06',
    ]),
    ep('EP-RT-021', 'SP-09', 'POST', '/app/retailer/cart/lines', 'retailer', null, [
        'name' => 'Add cart line',
        'name_ar' => 'إضافة للسلة',
        'b' => [
            'product_id' => 880,
            'variant_id' => 1,
            'qty' => 4,
            'source' => 'browse',
        ],
        'r' => $cart,
        'd' => 'source: browse|shortage|favorite|reorder|offer. Full cart is recalculated.',
    ]),
    ep('EP-RT-022', 'SP-09', 'PATCH', '/app/retailer/cart/lines/{id}', 'retailer', null, [
        'name' => 'Update cart qty',
        'name_ar' => 'تعديل كمية',
        'b' => ['qty' => 2],
        'r' => $cart + ['removed_offers' => []],
        'd' => 'Offers that lose their condition are listed in removed_offers (BR-20).',
    ]),
    ep('EP-RT-023', 'SP-09', 'DELETE', '/app/retailer/cart/lines/{id}', 'retailer', null, [
        'name' => 'Remove cart line',
        'name_ar' => 'حذف بند',
        'r' => $cart,
        'd' => 'Removing a line that belongs to an offer removes the whole offer (BR-08).',
    ]),
    ep('EP-RT-024', 'SP-09', 'PATCH', '/app/retailer/cart/sections/{ref}', 'retailer', null, [
        'name' => 'Update cart section',
        'name_ar' => 'ملاحظة/جدولة قسم',
        'b' => ['note' => 'الاتصال قبل الوصول', 'scheduled_at' => '2026-03-02T10:00:00+03:00'],
        'r' => $cart,
    ]),
    ep('EP-RT-025', 'SP-09', 'POST', '/app/retailer/cart/submit', 'retailer', null, [
        'name' => 'Submit cart',
        'name_ar' => 'إرسال الطلب',
        'b' => [
            'sections' => [[
                'ref' => 'ch_a1',
                'note' => 'الاتصال قبل الوصول',
                'scheduled_at' => null,
            ]],
            'client_created_at' => '2026-03-01T09:10:00+03:00',
            'offline_created' => false,
        ],
        'r' => [
            'order' => [
                'id' => 700,
                'order_no' => 'ORD-700',
                'sub_orders' => [
                    ['sub_order_no' => 'SO-9001', 'status' => 'pending', 'total' => 48000],
                ],
            ],
            'repricing_diff' => null,
        ],
        'd' => 'If offline_created=true the order is always accepted, then repriced; repricing_diff is shown (REQ-CM-018). Split is server-side (REQ-IN-08).',
        'in' => 'REQ-IN-08',
        'e' => [423 => 'credit_limit_exceeded', 409 => 'offer_no_longer_valid'],
    ]),

    ep('EP-RT-030', 'SP-09', 'GET', '/app/retailer/orders', 'retailer', null, [
        'name' => 'List orders',
        'name_ar' => 'طلباتي',
        'q' => listQuery([
            'filter[status]' => 'active',
            'filter[channel_id]' => '',
            'date_from' => '2026-02-01',
            'date_to' => '2026-03-01',
        ]),
        'r' => [[
            'id' => 9001,
            'sub_order_no' => 'SO-9001',
            'created_at' => '2026-03-01T09:10:00+03:00',
            'supply_channel' => null,
            'status' => 'pending',
            'total' => 48000,
            'can_cancel' => true,
            'can_reorder' => false,
        ]],
        'd' => 'filter[status]: all|active|pending|processing|delivered|cancelled. supply_channel is null until confirmed (REQ-IN-06).',
    ]),
    ep('EP-RT-031', 'SP-09', 'GET', '/app/retailer/orders/{id}', 'retailer', null, [
        'name' => 'Order detail',
        'name_ar' => 'تفاصيل طلب',
        'r' => [
            'lines' => [['id' => 1, 'name' => 'زيت دوار الشمس 1 لتر', 'qty' => 4, 'price' => 12000]],
            'invoice' => null,
            'timeline' => [['stage' => 'pending', 'at' => '2026-03-01T09:10:00+03:00']],
            'rep' => null,
        ],
        'd' => 'rep{name,phone} only when status is on_the_way (BR-03).',
    ]),
    ep('EP-RT-032', 'SP-09', 'POST', '/app/retailer/orders/{id}/cancel', 'retailer', null, [
        'name' => 'Cancel order',
        'name_ar' => 'إلغاء طلب',
        'b' => ['reason' => 'طلب بالخطأ'],
        'r' => ['status' => 'cancelled'],
        'e' => [409 => 'illegal_transition'],
        'd' => '409 unless status is pending (BR-06).',
    ]),
    ep('EP-RT-033', 'SP-09', 'POST', '/app/retailer/orders/{id}/reorder', 'retailer', null, [
        'name' => 'Reorder',
        'name_ar' => 'إعادة الطلب',
        'b' => ['modify' => false],
        'r' => ['cart' => $cart],
        'd' => 'Returns a cart repriced at today\'s prices.',
    ]),
    ep('EP-RT-034', 'SP-09', 'GET', '/app/retailer/orders/{id}/tracking', 'retailer', null, [
        'name' => 'Track order',
        'name_ar' => 'تتبع الطلب',
        'r' => [
            'stages' => [
                ['key' => 'pending', 'label' => 'معلق', 'at' => '2026-03-01T09:10:00+03:00'],
                ['key' => 'on_the_way', 'label' => 'في الطريق', 'at' => '2026-03-01T11:40:00+03:00'],
            ],
            'rep' => ['name' => 'أحمد', 'phone' => '+963955000000', 'lat' => 33.51, 'lng' => 36.28],
            'eta_minutes' => 22,
        ],
        'd' => 'Rep identity only at on_the_way (BR-03).',
    ]),

    ep('EP-RT-040', 'SP-12', 'GET', '/app/retailer/receipts/{subOrderId}', 'retailer', 'rt.receive.confirm', [
        'name' => 'Receiving list',
        'name_ar' => 'قائمة الاستلام',
        'r' => [
            'lines' => [[
                'id' => 1,
                'image' => null,
                'name' => 'زيت دوار الشمس 1 لتر',
                'brand' => 'نور',
                'variant' => null,
                'qty' => 4,
                'price' => 12000,
                'status' => 'pending',
            ]],
            'invoice_total' => 48000,
        ],
        'd' => 'Same payload the rep sees (REQ-IN-05).',
        'in' => 'REQ-IN-05',
    ]),
    ep('EP-RT-041', 'SP-12', 'PATCH', '/app/retailer/receipts/{id}/lines/{lineId}', 'retailer', 'rt.receive.confirm', [
        'name' => 'Adjust received line',
        'name_ar' => 'تعديل بند الاستلام',
        'b' => ['qty_received' => 3, 'action' => 'return', 'reason' => 'عبوة تالفة'],
        'r' => ['new_invoice_total' => 36000],
        'in' => 'REQ-IN-05',
    ]),
    ep('EP-RT-042', 'SP-12', 'POST', '/app/retailer/receipts/{id}/confirm', 'retailer', 'rt.receive.confirm', [
        'name' => 'Confirm receipt',
        'name_ar' => 'تأكيد الاستلام',
        'b' => [
            'lines' => [['line_id' => 1, 'qty_received' => 4, 'action' => 'accept']],
        ],
        'r' => [
            'invoice' => ['no' => 'INV-501', 'total' => 48000],
            'ask_payment' => true,
        ],
        'in' => 'REQ-IN-05',
    ]),
    ep('EP-RT-043', 'SP-12', 'POST', '/app/retailer/return-requests', 'retailer', 'rt.receive.return_request', [
        'name' => 'Create return/exchange',
        'name_ar' => 'طلب إرجاع/استبدال',
        'b' => [
            'sub_order_id' => 9001,
            'type' => 'return',
            'lines' => [['line_id' => 1, 'qty' => 1, 'reason' => 'تالف', 'photos' => []]],
        ],
        'r' => ['request_no' => 'RR-200', 'status' => 'pending'],
        'in' => 'REQ-IN-04',
    ]),
    ep('EP-RT-044', 'SP-12', 'GET', '/app/retailer/return-requests', 'retailer', null, [
        'name' => 'List return requests',
        'name_ar' => 'مرتجعاتي',
        'q' => listQuery(['filter[status]' => 'pending', 'filter[channel_id]' => '1', 'date_from' => '2026-02-01']),
        'r' => [['request_no' => 'RR-200', 'type' => 'return', 'status' => 'pending']],
    ]),
    ep('EP-RT-045', 'SP-12', 'POST', '/app/retailer/reps/{id}/rate', 'retailer', null, [
        'name' => 'Rate rep',
        'name_ar' => 'تقييم المندوب',
        'b' => [
            'stars' => 5,
            'note' => 'سريع ومهذب',
            'tags' => ['fast', 'polite', 'intact'],
        ],
        'r' => ['success' => true],
        'd' => 'tags: fast|polite|intact|late|damaged',
    ]),

    ep('EP-RT-050', 'SP-13', 'POST', '/app/retailer/payments', 'retailer', 'rt.payment.record', [
        'name' => 'Record payment',
        'name_ar' => 'تسجيل دفعة',
        'b' => [
            'receipt_no' => 'RCPT-10041',
            'rep_id' => 70,
            'supply_channel_id' => 1,
            'invoice_no' => 'INV-501',
            'amount' => 48000,
        ],
        'r' => ['payment' => ['id' => 301], 'retailer_receivable' => 0],
        'e' => [409 => 'duplicate_receipt_no'],
        'd' => 'receipt_no comes from the rep app. Duplicate → 409 always (REQ-IN-01).',
        'in' => 'REQ-IN-01',
    ]),
    ep('EP-RT-051', 'SP-13', 'GET', '/app/retailer/account/summary', 'retailer', null, [
        'name' => 'Account summary',
        'name_ar' => 'ملخص الحساب',
        'q' => ['month' => '2026-03'],
        'r' => [
            'month' => '2026-03',
            'orders_total' => 210000,
            'purchases_total' => 198000,
            'orders_count' => 6,
            'avg_order_value' => 35000,
            'debt_total' => 48000,
            'payments_total' => 150000,
            'points' => 1240,
        ],
        'd' => 'From daily snapshots, not a live join (TB-RT-070 / BR-AD-23).',
    ]),
    ep('EP-RT-052', 'SP-13', 'GET', '/app/retailer/account/statement', 'retailer', 'rt.account.statement', [
        'name' => 'Account statement',
        'name_ar' => 'كشف الحساب',
        'q' => ['date_from' => '2026-02-01', 'date_to' => '2026-02-28', 'channel_id' => '1'],
        'r' => [
            'opening_balance' => 12000,
            'rows' => [[
                'date' => '2026-02-03',
                'type' => 'invoice',
                'ref_no' => 'INV-480',
                'debit' => 36000,
                'credit' => 0,
                'balance' => 48000,
            ]],
            'closing_balance' => 48000,
        ],
        'd' => 'Invariant: retailer.receivable == SUM(invoices) − SUM(payments) − SUM(credit_notes) (AC-07).',
    ]),
    ep('EP-RT-053', 'SP-13', 'POST', '/app/retailer/account/statement/export', 'retailer', 'rt.account.statement', [
        'name' => 'Export statement',
        'name_ar' => 'تصدير الكشف',
        'b' => ['date_from' => '2026-02-01', 'date_to' => '2026-02-28', 'channel_id' => 1, 'format' => 'pdf'],
        'r' => ['job_id' => 'job_stmt_1'],
        'd' => 'Then poll exports; download_url lasts 24h.',
    ]),
    ep('EP-RT-054', 'SP-13', 'GET', '/app/retailer/debts', 'retailer', null, [
        'name' => 'Debts by channel',
        'name_ar' => 'الذمم',
        'r' => [
            'by_channel' => [[
                'channel' => ['id' => 1, 'name' => 'شركة النور'],
                'total' => 48000,
                'overdue' => 0,
                'invoices' => [['no' => 'INV-501', 'total' => 48000, 'remaining' => 48000]],
            ]],
        ],
        'd' => 'Channel name is visible here because invoices exist (after confirm).',
    ]),

    ep('EP-RT-070A', 'SP-06', 'GET', '/app/retailer/shortages', 'retailer', null, [
        'name' => 'List shortages',
        'name_ar' => 'النواقص',
        'q' => listQuery(),
        'r' => [['id' => 5, 'product_id' => 880, 'name' => 'زيت دوار الشمس 1 لتر', 'note' => 'نفد من الرف']],
        'd' => 'DOC-12A TB-RT-031. Synced via EP-SY-002.',
    ]),
    ep('EP-RT-070B', 'SP-06', 'POST', '/app/retailer/shortages', 'retailer', null, [
        'name' => 'Add shortage',
        'name_ar' => 'إضافة ناقص',
        'b' => ['product_id' => 880, 'note' => 'نفد من الرف'],
        'r' => ['id' => 5],
        'd' => 'DOC-12A TB-RT-031.',
    ]),
    ep('EP-RT-070C', 'SP-06', 'DELETE', '/app/retailer/shortages/{id}', 'retailer', null, [
        'name' => 'Remove shortage',
        'name_ar' => 'حذف ناقص',
        'r' => ['success' => true],
        'd' => 'DOC-12A TB-RT-031.',
    ]),
];
