<?php

declare(strict_types=1);

return [
    ep('EP-AD-025', 'SP-02', 'GET', '/platform/iam/approval-requests', 'platform', 'ad.iam.view_catalog', [
        'name' => 'Dual-approval inbox',
        'name_ar' => 'طلبات الاعتماد المزدوج',
        'q' => listQuery(['filter[status]' => 'pending']),
        'r' => [[
            'id' => 19,
            'permission' => 'ad.channels.delete',
            'action' => 'channel.delete',
            'requested_by' => 1,
            'payload' => ['channel_id' => 9],
            'status' => 'pending',
            'created_at' => '2026-03-01T09:00:00+03:00',
        ]],
        'd' => 'DOC-12E TB-AD-007 / AC-PM-05. The 21 dual-approval permissions create a request instead of executing.',
        'dual' => true,
    ]),
    ep('EP-AD-026', 'SP-02', 'POST', '/platform/iam/approval-requests/{id}/decide', 'platform', 'ad.iam.role_approve', [
        'name' => 'Decide dual-approval request',
        'name_ar' => 'بتّ طلب اعتماد',
        'b' => ['decision' => 'approve', 'reason' => 'مراجعة مكتملة'],
        'r' => ['status' => 'approved', 'executed' => true],
        'e' => [403 => 'sod_violation'],
        'd' => 'Approver cannot be the requester.',
        'dual' => true,
        'crit' => true,
    ]),
    ep('EP-AD-027', 'SP-02', 'POST', '/platform/iam/roles/preview', 'platform', 'ad.iam.view_catalog', [
        'name' => 'Preview role in business language',
        'name_ar' => 'معاينة أثر الدور',
        'b' => ['permissions' => ['sc.orders.confirm', 'sc.pricing.update']],
        'r' => [
            'summary_ar' => 'سيستطيع تأكيد الطلبات وتغيير أسعار المناطق',
            'sod_conflicts' => [],
        ],
        'd' => 'DOC-12E TB-AD-143.',
    ]),
    ep('EP-AD-028', 'SP-02', 'GET', '/platform/iam/reviews/{id}', 'platform', 'ad.audit.review', [
        'name' => 'Access-review campaign',
        'name_ar' => 'حملة مراجعة الصلاحيات',
        'r' => [
            'campaign_id' => 3,
            'quarter' => '2026-Q1',
            'status' => 'open',
            'items' => [[
                'id' => 11,
                'user_id' => 4,
                'role_id' => 2,
                'suggestion' => 'revoke_unused',
                'decision' => null,
            ]],
        ],
        'd' => 'DOC-12E TB-AD-115/153. Campaign cannot close until every item is decided.',
    ]),
    ep('EP-AD-029', 'SP-02', 'POST', '/platform/iam/reviews/{id}/items/{itemId}/decide', 'platform', 'ad.audit.review', [
        'name' => 'Decide review item',
        'name_ar' => 'تأكيد أو سحب بند المراجعة',
        'b' => ['decision' => 'keep', 'reason' => 'ما زال مدير قناة فعّال'],
        'r' => ['item_id' => 11, 'decision' => 'keep'],
        'd' => 'decision: keep|revoke. DOC-12E TF-AD-115.',
    ]),

    ep('EP-AD-042A', 'SP-03', 'PUT', '/platform/refs/governorates/{id}', 'platform', 'ad.refs.update', [
        'name' => 'Update governorate',
        'name_ar' => 'تعديل محافظة',
        'b' => ['name' => 'ريف دمشق', 'order' => 2, 'reason' => 'تصحيح التسمية'],
        'r' => ['id' => 2],
        'd' => 'DOC-12E TB-AD-046. Every ref change requires a reason and is audited before/after.',
    ]),
    ep('EP-AD-042B', 'SP-03', 'PUT', '/platform/refs/zones/{id}', 'platform', 'ad.refs.update', [
        'name' => 'Update zone',
        'name_ar' => 'تعديل منطقة',
        'b' => [
            'name' => 'المزة',
            'district' => 'المزة',
            'polygon' => null,
            'order' => 3,
            'reason' => 'تعديل الحي',
        ],
        'r' => ['id' => 12],
    ]),
    ep('EP-AD-042C', 'SP-03', 'PUT', '/platform/refs/activity-types/{id}', 'platform', 'ad.refs.update', [
        'name' => 'Update activity type',
        'name_ar' => 'تعديل نوع نشاط',
        'b' => ['name' => 'بقالة', 'icon' => 'grocery', 'reason' => 'تحديث الأيقونة'],
        'r' => ['id' => 3],
        'd' => 'Hard delete of an in-use ref is rejected (REQ-AD-030).',
    ]),
    ep('EP-AD-042D', 'SP-03', 'PUT', '/platform/refs/root-categories/{id}', 'platform', 'ad.refs.update', [
        'name' => 'Update root category',
        'name_ar' => 'تعديل فئة جذر',
        'b' => ['name' => 'مواد غذائية', 'order' => 1, 'reason' => 'إعادة ترتيب'],
        'r' => ['id' => 10],
    ]),
    ep('EP-AD-042E', 'SP-03', 'PUT', '/platform/refs/sale-units/{id}', 'platform', 'ad.refs.update', [
        'name' => 'Update sale unit',
        'name_ar' => 'تعديل وحدة بيع',
        'b' => ['name' => 'قطعة', 'abbr' => 'pcs', 'default_factor' => 1, 'reason' => 'توحيد الاختصار'],
        'r' => ['id' => 3],
    ]),
    ep('EP-AD-042F', 'SP-03', 'PUT', '/platform/refs/equipments/{id}', 'platform', 'ad.refs.update', [
        'name' => 'Update equipment',
        'name_ar' => 'تعديل تجهيز',
        'b' => ['name' => 'ثلاجة عرض', 'icon' => 'fridge', 'reason' => 'تصحيح'],
        'r' => ['id' => 1],
    ]),
    ep('EP-AD-042G', 'SP-03', 'PUT', '/platform/refs/currencies/{id}', 'platform', 'ad.refs.currency', [
        'name' => 'Update currency',
        'name_ar' => 'تعديل عملة',
        'b' => ['name' => 'ليرة سورية', 'decimals' => 0, 'is_display_currency' => true, 'reason' => 'تعيين عملة العرض'],
        'r' => ['id' => 1],
    ]),

    ep('EP-AD-059A', 'SP-04', 'POST', '/platform/channels/bulk-plan/preview', 'platform', 'ad.billing.assign_plan', [
        'name' => 'Preview bulk plan change',
        'name_ar' => 'معاينة تغيير الباقة الجماعي',
        'b' => ['channel_ids' => [1, 2, 9], 'plan_id' => 3, 'cycle' => 'yearly'],
        'r' => [
            'channels_count' => 3,
            'current_mrr' => 75000000,
            'new_mrr' => 225000000,
            'delta' => 150000000,
            'blocked' => [],
        ],
        'd' => 'DOC-12E TB-AD-031. Up to 50 channels. Show revenue impact before execute.',
    ]),
    ep('EP-AD-059B', 'SP-04', 'POST', '/platform/channels/bulk-plan', 'platform', 'ad.billing.assign_plan', [
        'name' => 'Apply bulk plan change',
        'name_ar' => 'تطبيق تغيير الباقة الجماعي',
        'b' => [
            'channel_ids' => [1, 2, 9],
            'plan_id' => 3,
            'cycle' => 'yearly',
            'reason' => 'ترقية موسم رمضان',
        ],
        'r' => ['updated' => [1, 2, 9]],
        'd' => 'DOC-12E TB-AD-031.',
    ]),
    ep('EP-AD-059C', 'SP-04', 'POST', '/platform/channels/export', 'platform', 'ad.channels.export', [
        'name' => 'Export channels list',
        'name_ar' => 'تصدير قائمة القنوات',
        'b' => [
            'filters' => ['status' => 'active', 'plan_id' => 2],
            'format' => 'csv',
        ],
        'r' => ['job_id' => 'job_ch_list_1'],
        'd' => 'DOC-12E TB-AD-032. Respects active filters, not the visible page. Background job.',
    ]),

    ep('EP-AD-081', 'SP-14', 'POST', '/platform/notifications', 'platform', 'ad.notify.send', [
        'name' => 'Create targeted platform notification',
        'name_ar' => 'إنشاء إشعار منصة',
        'b' => [
            'title' => 'تحديث شروط الاستخدام',
            'body' => 'يرجى مراجعة الشروط المحدّثة',
            'action' => ['type' => 'legal', 'target' => 'terms'],
            'targeting' => [
                'level' => 'user_type',
                'user_types' => ['retailer', 'rep'],
                'channel_ids' => [],
                'zone_ids' => [],
                'activity_type_ids' => [],
            ],
            'channels' => ['push', 'in_app'],
            'scheduled_at' => null,
        ],
        'r' => ['id' => 502, 'status' => 'queued', 'estimated_recipients' => 12400],
        'd' => 'DOC-12E TB-AD-090/091. Seven targeting levels. Broadcast-all still uses EP-AD-080 + dual approval.',
    ]),
    ep('EP-AD-082', 'SP-14', 'POST', '/platform/notifications/preview', 'platform', 'ad.notify.send', [
        'name' => 'Preview notification targeting',
        'name_ar' => 'تقييم استهداف الإشعار',
        'b' => [
            'targeting' => ['level' => 'channel', 'channel_ids' => [1, 9]],
        ],
        'r' => ['recipients' => 840, 'by_type' => ['retailer' => 720, 'rep' => 90, 'channel' => 30]],
        'd' => 'DOC-12E TB-AD-091.',
    ]),
    ep('EP-AD-083A', 'SP-14', 'GET', '/platform/notifications/templates', 'platform', 'ad.notify.view', [
        'name' => 'Platform notification templates',
        'name_ar' => 'قوالب إشعارات المنصة',
        'r' => [[
            'event_key' => 'channel.suspended',
            'title' => 'تم تعطيل قناتك',
            'enabled' => true,
            'channels' => ['push', 'in_app'],
        ]],
        'd' => 'DOC-12E TB-AD-093. Events: channel disabled, terms update, new version, scheduled maintenance.',
    ]),
    ep('EP-AD-083B', 'SP-14', 'PUT', '/platform/notifications/templates', 'platform', 'ad.notify.send', [
        'name' => 'Upsert platform notification template',
        'name_ar' => 'تحديث قالب منصة',
        'b' => [
            'event_key' => 'legal.updated',
            'title' => 'تحديث سياسة الخصوصية',
            'body' => 'يلزم قبول السياسة الجديدة للمتابعة',
            'enabled' => true,
            'channels' => ['in_app'],
        ],
        'r' => ['event_key' => 'legal.updated'],
    ]),
    ep('EP-AD-084', 'SP-14', 'GET', '/platform/notifications/log', 'platform', 'ad.notify.view', [
        'name' => 'Platform notification log',
        'name_ar' => 'سجل إرسال المنصة',
        'q' => listQuery(['filter[status]' => 'failed']),
        'r' => [[
            'at' => '2026-03-01T09:12:00+03:00',
            'recipient_type' => 'retailer',
            'recipient_id' => 481,
            'template' => 'legal.updated',
            'status' => 'sent',
            'failure_reason' => null,
        ]],
        'd' => 'DOC-12E TB-AD-094.',
    ]),

    ep('EP-AD-093', 'SP-16', 'POST', '/platform/reports/{type}/export', 'platform', 'ad.reports.export', [
        'name' => 'Export platform report',
        'name_ar' => 'تصدير تقرير المنصة',
        'b' => [
            'format' => 'xlsx',
            'filters' => ['date_from' => '2026-02-01', 'date_to' => '2026-02-28'],
        ],
        'r' => ['job_id' => 'job_ad_rep_1'],
        'd' => 'DOC-12E TB-AD-121. Excel/PDF. Heavy jobs notify with EP-AD-092 download_url (24h).',
    ]),
    ep('EP-AD-094', 'SP-16', 'GET', '/platform/dashboard/alerts', 'platform', 'ad.dashboard.view', [
        'name' => 'Realtime platform alerts',
        'name_ar' => 'تنبيهات المنصة اللحظية',
        'r' => [
            ['type' => 'queue_backlog', 'priority' => 'high', 'count' => 2, 'action_url' => '/platform/system/queues'],
            ['type' => 'integration_fail', 'priority' => 'critical', 'count' => 1, 'action_url' => '/platform/system/integrations'],
            ['type' => 'channel_idle', 'priority' => 'medium', 'count' => 3, 'action_url' => '/platform/channels?filter[idle]=1'],
        ],
        'd' => 'DOC-12E TB-AD-021. Nine alert types. Live (queues/errors/integrations) are not from the nightly snapshot. REQ-AD-012.',
    ]),
    ep('EP-AD-095', 'SP-16', 'GET', '/platform/dashboard/cards/{key}', 'platform', 'ad.dashboard.view', [
        'name' => 'Dashboard card (isolated)',
        'name_ar' => 'بطاقة لوحة مستقلة',
        'q' => ['range' => '30d'],
        'r' => ['key' => 'gmv', 'value' => 9800000000, 'delta' => 0.12],
        'd' => 'DOC-12E TB-AD-023. One card failing must not take down the page. key ∈ channels|retailers|reps|orders|gmv|platform_revenue|integrations_health|sync.',
        'e' => [404 => 'not_found'],
    ]),

    ep('EP-AD-106', 'SP-17', 'POST', '/platform/platform-invoices/{id}/credit-note', 'platform', 'ad.billing.invoice', [
        'name' => 'Platform invoice credit note',
        'name_ar' => 'مذكرة دائنة لفاتورة منصة',
        'b' => ['amount' => 5000000, 'reason' => 'تعويض انقطاع خدمة'],
        'r' => ['credit_note_id' => 12, 'invoice_id' => 40],
        'd' => 'DOC-12E TB-AD-062. Posted invoices are immutable; correction is a linked credit note (REQ-AD-053).',
        'dual' => true,
        'crit' => true,
    ]),
    ep('EP-AD-107', 'SP-17', 'GET', '/platform/billing/revenue', 'platform', 'ad.billing.view', [
        'name' => 'Platform revenue report',
        'name_ar' => 'تقرير إيراد المنصة',
        'q' => ['date_from' => '2026-01-01', 'date_to' => '2026-03-01', 'exclude_internal' => '1'],
        'r' => [
            'recognized' => 185000000,
            'excluded_internal' => 12000000,
            'excluded_trial' => 4000000,
            'by_plan' => [['plan' => 'growth', 'amount' => 140000000]],
        ],
        'd' => 'DOC-12E TB-AD-064 / REQ-AD-054. Internal and trial channels excluded with an explicit flag.',
    ]),

    ep('EP-AD-114', 'SP-17', 'DELETE', '/platform/features/{key}/override', 'platform', 'ad.features.override', [
        'name' => 'Clear feature override',
        'name_ar' => 'إعادة الميزة لقيمة الباقة',
        'b' => ['channel_id' => 1, 'reason' => 'انتهاء التجربة'],
        'r' => ['key' => 'rep_live_tracking', 'channel_id' => 1, 'source' => 'plan'],
        'd' => 'DOC-12E TB-AD-072. Precedence: manual override ← plan ← global.',
    ]),
    ep('EP-AD-115', 'SP-17', 'GET', '/platform/app-versions', 'platform', 'ad.content.view', [
        'name' => 'List app versions',
        'name_ar' => 'سجل إصدارات التطبيقات',
        'q' => listQuery(['filter[app]' => 'retailer', 'filter[platform]' => 'android']),
        'r' => [[
            'id' => 14,
            'app' => 'retailer',
            'platform' => 'android',
            'version' => '1.4.3',
            'build' => 143,
            'min_supported' => '1.3.0',
            'rollout' => 25,
            'force_update' => false,
        ]],
        'd' => 'DOC-12E TB-AD-084.',
    ]),

    ep('EP-AD-126', 'SP-17', 'POST', '/platform/support/users/{id}/disable', 'platform', 'ad.support.disable_user', [
        'name' => 'Temporarily disable user',
        'name_ar' => 'تعطيل مستخدم مؤقت',
        'b' => [
            'user_type' => 'retailer',
            'reason' => 'بلاغ احتيال قيد التحقيق',
            'until' => '2026-03-08T00:00:00+03:00',
        ],
        'r' => ['status' => 'disabled', 'sessions_revoked' => 2],
        'd' => 'DOC-12E TB-AD-052. One of the five support actions. Sessions revoked immediately (BR-AD-07).',
        'crit' => true,
    ]),
    ep('EP-AD-127', 'SP-17', 'POST', '/platform/support/users/{id}/reset-device', 'platform', 'ad.support.revoke_sessions', [
        'name' => 'Reset bound device',
        'name_ar' => 'إعادة تعيين جهاز المستخدم',
        'b' => ['user_type' => 'retailer', 'reason' => 'استبدال الهاتف'],
        'r' => ['devices_cleared' => 1, 'sessions_revoked' => 1],
        'd' => 'DOC-12E TB-AD-052. Fifth support action set: resend OTP, revoke sessions, reset device, disable, impersonate.',
        'crit' => true,
    ]),
    ep('EP-AD-128', 'SP-17', 'PATCH', '/platform/support/tickets/{id}', 'platform', 'ad.support.tickets', [
        'name' => 'Update support ticket',
        'name_ar' => 'تحديث تذكرة',
        'b' => [
            'status' => 'resolved',
            'assignee_id' => 4,
            'priority' => 'high',
            'resolution' => 'أُعيد إرسال OTP وأُبطلت الجلسات',
            'root_cause' => 'جهاز جديد بدون فك الربط',
        ],
        'r' => ['id' => 512, 'status' => 'resolved'],
        'd' => 'DOC-12E TB-AD-056. Six-state ticket lifecycle.',
    ]),

    ep('EP-AD-137', 'SP-17', 'GET', '/platform/system/scheduled-jobs', 'platform', 'ad.system.view', [
        'name' => 'Scheduled jobs',
        'name_ar' => 'المهام المجدولة',
        'r' => [[
            'name' => 'snapshots:daily',
            'cron' => '0 2 * * *',
            'last_run_at' => '2026-03-01T02:00:11+03:00',
            'last_result' => 'ok',
            'duration_ms' => 18420,
            'next_run_at' => '2026-03-02T02:00:00+03:00',
            'missed_cycles' => 0,
        ]],
        'd' => 'DOC-12E TB-AD-101. Alert when three consecutive cycles are skipped.',
    ]),
    ep('EP-AD-138', 'SP-17', 'GET', '/platform/system/storage', 'platform', 'ad.system.view', [
        'name' => 'Storage and backups',
        'name_ar' => 'التخزين والنسخ',
        'r' => [
            'disk_used_percent' => 61,
            'database_size_gb' => 42.5,
            'last_backup_at' => '2026-03-01T03:10:00+03:00',
            'last_backup_status' => 'ok',
            'last_restore_test_at' => '2026-02-23T04:00:00+03:00',
            'last_restore_test_status' => 'ok',
        ],
        'd' => 'DOC-12E TB-AD-105. Alert below 15% free disk or failed backup.',
    ]),

    ep('EP-AD-140A', 'SP-17', 'GET', '/platform/content/legal', 'platform', 'ad.content.view', [
        'name' => 'List legal documents',
        'name_ar' => 'الشروط والخصوصية',
        'q' => ['type' => 'privacy'],
        'r' => [[
            'id' => 8,
            'type' => 'privacy',
            'version' => '2026-03',
            'effective_from' => '2026-03-15',
            'approved_by' => 1,
            'requires_reconsent' => true,
        ]],
        'd' => 'DOC-12E TB-AD-080.',
    ]),
    ep('EP-AD-140B', 'SP-17', 'POST', '/platform/content/legal', 'platform', 'ad.content.manage', [
        'name' => 'Publish legal version',
        'name_ar' => 'نشر نسخة شروط/خصوصية',
        'b' => [
            'type' => 'privacy',
            'body_ar' => '…',
            'effective_from' => '2026-03-15',
            'requires_reconsent' => true,
            'reason' => 'تحديث بنود البيانات',
        ],
        'r' => ['id' => 9, 'version' => '2026-03'],
        'd' => 'DOC-12E TB-AD-081. Sets requires_legal_accept on EP-CM-004 until the user consents.',
        'crit' => true,
        'dual' => true,
    ]),
    ep('EP-AD-141A', 'SP-17', 'GET', '/platform/content/intro', 'platform', 'ad.content.view', [
        'name' => 'Default intro',
        'name_ar' => 'الانترو الافتراضي للمنصة',
        'r' => [
            'enabled' => true,
            'media_type' => 'video',
            'media_id' => 'media_intro_default',
            'targeting' => ['activity_type_ids' => [3], 'zone_ids' => []],
        ],
        'd' => 'DOC-12E TB-AD-082. Used when the channel has no intro.',
    ]),
    ep('EP-AD-141B', 'SP-17', 'PUT', '/platform/content/intro', 'platform', 'ad.content.manage', [
        'name' => 'Update default intro',
        'name_ar' => 'تحديث الانترو الافتراضي',
        'b' => [
            'enabled' => true,
            'text' => 'مرحباً في منصة التوزيع',
            'media_type' => 'video',
            'media_id' => 'media_intro_default',
            'duration' => 8,
            'targeting' => ['activity_type_ids' => [3], 'zone_ids' => []],
        ],
        'r' => ['enabled' => true],
    ]),
    ep('EP-AD-142A', 'SP-17', 'GET', '/platform/content/help', 'platform', 'ad.content.view', [
        'name' => 'Help articles',
        'name_ar' => 'الأدلة والمساعدة',
        'q' => listQuery(['filter[audience]' => 'retailer']),
        'r' => [['id' => 3, 'audience' => 'retailer', 'title' => 'كيف أرسل طلباً', 'status' => 'published']],
        'd' => 'DOC-12E TB-AD-083 / NEED-C-09.',
    ]),
    ep('EP-AD-142B', 'SP-17', 'POST', '/platform/content/help', 'platform', 'ad.content.manage', [
        'name' => 'Create help article',
        'name_ar' => 'إنشاء مقال مساعدة',
        'b' => [
            'audience' => 'retailer',
            'title' => 'كيف أرسل طلباً',
            'body' => '…',
            'status' => 'published',
        ],
        'r' => ['id' => 3],
    ]),

    ep('EP-AD-150A', 'SP-17', 'GET', '/platform/settings/profile', 'platform', 'ad.settings.view', [
        'name' => 'Platform profile',
        'name_ar' => 'الملف العام للمنصة',
        'r' => [
            'name_ar' => 'منصة التوزيع',
            'name_en' => 'B2B Distribution',
            'support_phone' => '+963110000000',
            'support_email' => 'support@platform.sy',
            'logo' => null,
            'timezone' => 'Asia/Damascus',
            'locale' => 'ar',
        ],
        'd' => 'DOC-12E TB-AD-130. Seven profile fields.',
    ]),
    ep('EP-AD-150B', 'SP-17', 'PUT', '/platform/settings/profile', 'platform', 'ad.settings.update', [
        'name' => 'Update platform profile',
        'name_ar' => 'تحديث الملف العام',
        'b' => [
            'name_ar' => 'منصة التوزيع',
            'name_en' => 'B2B Distribution',
            'support_phone' => '+963110000000',
            'support_email' => 'support@platform.sy',
            'logo' => null,
            'timezone' => 'Asia/Damascus',
            'locale' => 'ar',
        ],
        'r' => ['updated' => true],
    ]),
    ep('EP-AD-151A', 'SP-17', 'GET', '/platform/settings/integrations', 'platform', 'ad.settings.view', [
        'name' => 'Integration credentials (masked)',
        'name_ar' => 'مفاتيح التكاملات',
        'r' => [[
            'provider' => 'whatsapp',
            'configured' => true,
            'secret_masked' => '****4412',
            'last_tested_at' => '2026-03-01T08:00:00+03:00',
            'last_test_ok' => true,
        ]],
        'd' => 'DOC-12E TB-AD-132 / BR-AD-21. Secrets are write-only after save. Audit stores masked values.',
    ]),
    ep('EP-AD-151B', 'SP-17', 'PUT', '/platform/settings/integrations/{provider}', 'platform', 'ad.settings.update', [
        'name' => 'Save integration credentials',
        'name_ar' => 'حفظ مفتاح تكامل',
        'b' => ['api_key' => '********', 'sender_id' => 'B2B'],
        'r' => ['provider' => 'whatsapp', 'configured' => true],
        'crit' => true,
        'd' => 'Must call test-connection first (TB-AD-131).',
    ]),
    ep('EP-AD-152', 'SP-17', 'POST', '/platform/settings/integrations/{provider}/test', 'platform', 'ad.settings.update', [
        'name' => 'Test integration connection',
        'name_ar' => 'اختبار اتصال المزوّد',
        'b' => new stdClass(),
        'r' => ['ok' => true, 'latency_ms' => 420],
        'd' => 'DOC-12E TB-AD-131. Mandatory before save.',
        'e' => [422 => 'validation_failed'],
    ]),
    ep('EP-AD-153A', 'SP-17', 'GET', '/platform/settings/channel-defaults', 'platform', 'ad.settings.view', [
        'name' => 'Default channel provisioning',
        'name_ar' => 'التهيئة الافتراضية للقنوات',
        'r' => [
            'copy_refs' => true,
            'default_plan_id' => 2,
            'default_roles' => ['channel_manager', 'sales_manager', 'catalog_manager', 'accountant', 'warehouse_keeper'],
            'trial_days' => 14,
        ],
        'd' => 'DOC-12E TB-AD-133. Used by channel provisioning.',
    ]),
    ep('EP-AD-153B', 'SP-17', 'PUT', '/platform/settings/channel-defaults', 'platform', 'ad.settings.update', [
        'name' => 'Update channel defaults',
        'name_ar' => 'تحديث تهيئة القنوات',
        'b' => [
            'copy_refs' => true,
            'default_plan_id' => 2,
            'default_roles' => ['channel_manager', 'sales_manager', 'catalog_manager', 'accountant', 'warehouse_keeper'],
            'trial_days' => 14,
        ],
        'r' => ['updated' => true],
    ]),
    ep('EP-AD-154', 'SP-17', 'GET', '/platform/team', 'platform', 'ad.team.view', [
        'name' => 'Platform team',
        'name_ar' => 'فريق المنصة',
        'q' => listQuery(),
        'r' => [[
            'id' => 1,
            'name' => 'منصّة',
            'email' => 'admin@platform.sy',
            'roles' => ['platform_admin'],
            'status' => 'active',
            'two_factor_enabled' => true,
        ]],
        'd' => 'DOC-12E TB-AD-134. Last active platform admin cannot be disabled or deleted (BR-AD-06, AC-AD-15).',
    ]),
    ep('EP-AD-155', 'SP-17', 'POST', '/platform/team/invites', 'platform', 'ad.team.invite', [
        'name' => 'Invite platform member',
        'name_ar' => 'دعوة عضو للمنصة',
        'b' => [
            'name' => 'سارة الدعم',
            'email' => 'sara@platform.sy',
            'role_ids' => [5],
        ],
        'r' => ['invite_id' => 22, 'status' => 'pending'],
        'd' => 'ad.team.* — pending invites live here until accepted.',
    ]),
    ep('EP-AD-156', 'SP-17', 'GET', '/platform/team/invites', 'platform', 'ad.team.view', [
        'name' => 'Pending invites',
        'name_ar' => 'الدعوات المعلّقة',
        'r' => [['id' => 22, 'email' => 'sara@platform.sy', 'status' => 'pending', 'role' => 'support']],
    ]),
    ep('EP-AD-157', 'SP-17', 'POST', '/platform/team/{id}/disable', 'platform', 'ad.team.delete', [
        'name' => 'Disable platform member',
        'name_ar' => 'تعطيل عضو منصة',
        'b' => ['reason' => 'ترك العمل'],
        'r' => ['status' => 'disabled', 'sessions_revoked' => 3],
        'e' => [409 => 'illegal_transition'],
        'd' => 'DOC-12E TB-AD-136 / BR-AD-07. Revokes every session and token within seconds. Last active admin → 409.',
        'crit' => true,
        'dual' => true,
    ]),
    ep('EP-AD-158A', 'SP-17', 'GET', '/platform/settings/security', 'platform', 'ad.settings.security', [
        'name' => 'Security policy',
        'name_ar' => 'سياسة أمان المنصة',
        'r' => [
            'session_minutes' => 480,
            'require_2fa' => true,
            'ip_allowlist' => [],
            'password_min_length' => 12,
            'password_require_mixed' => true,
            'max_login_attempts' => 5,
        ],
        'd' => 'DOC-12E TB-AD-135.',
    ]),
    ep('EP-AD-158B', 'SP-17', 'PUT', '/platform/settings/security', 'platform', 'ad.settings.security', [
        'name' => 'Update security policy',
        'name_ar' => 'تحديث سياسة الأمان',
        'b' => [
            'session_minutes' => 480,
            'require_2fa' => true,
            'ip_allowlist' => ['185.1.2.0/24'],
            'password_min_length' => 12,
            'password_require_mixed' => true,
            'max_login_attempts' => 5,
            'reason' => 'تضييق الدخول على مكتب المنصة',
        ],
        'r' => ['updated' => true],
        'd' => 'DOC-12E TB-AD-135. Critical + dual approval. ad.settings.security.',
        'crit' => true,
        'dual' => true,
    ]),
];
