<?php

declare(strict_types=1);

/**
 * DOC-07 / AD-FSD gaps: channel card tabs, join flow, ref status,
 * dashboard charts, plans CRUD, notify campaigns, backups, my profile, team.
 */
return [
    ep('EP-AD-043A', 'SP-03', 'PATCH', '/platform/refs/governorates/{id}/status', 'platform', 'ad.refs.disable', [
        'name' => 'Change governorate status',
        'name_ar' => 'تعطيل/تفعيل محافظة',
        'b' => ['status' => 'disabled', 'reason' => 'إعادة ترسيم إداري'],
        'r' => ['affected' => ['zones' => 18, 'retailers' => 240, 'channels' => 4]],
        'd' => 'DOC-07 §4.3.1 — المحافظات لا تُحذف، تُعطَّل فقط. REQ-AD-030 / REQ-AD-031.',
        'crit' => true,
    ]),
    ep('EP-AD-043B', 'SP-03', 'PATCH', '/platform/refs/activity-types/{id}/status', 'platform', 'ad.refs.disable', [
        'name' => 'Change activity type status',
        'name_ar' => 'تعطيل/تفعيل نوع نشاط',
        'b' => ['status' => 'disabled', 'reason' => 'نشاط مهجور'],
        'r' => ['affected' => ['retailers' => 40, 'channels' => 2]],
        'd' => 'تعطيله يخفي المرتبط به ولا يحذف حساباً.',
        'crit' => true,
    ]),
    ep('EP-AD-043C', 'SP-03', 'PATCH', '/platform/refs/root-categories/{id}/status', 'platform', 'ad.refs.disable', [
        'name' => 'Change root category status',
        'name_ar' => 'تعطيل/تفعيل فئة جذر',
        'b' => ['status' => 'disabled', 'reason' => 'دمج فئات'],
        'r' => ['affected' => ['child_categories' => 12, 'active_products' => 310]],
        'e' => [409 => 'ref_in_use'],
        'd' => 'AC-AD-11: رفض التعطيل إن تحتها فئات أو منتجات نشطة، مع عرض العدد المتأثر.',
        'crit' => true,
    ]),
    ep('EP-AD-043D', 'SP-03', 'PATCH', '/platform/refs/sale-units/{id}/status', 'platform', 'ad.refs.disable', [
        'name' => 'Change sale unit status',
        'name_ar' => 'تعطيل/تفعيل وحدة بيع',
        'b' => ['status' => 'disabled', 'reason' => 'وحدة مهجورة'],
        'r' => ['affected' => ['products' => 0]],
        'e' => [409 => 'ref_in_use'],
        'd' => 'لا تُحذف وحدة مستخدَمة في أي منتج.',
        'crit' => true,
    ]),
    ep('EP-AD-043E', 'SP-03', 'PATCH', '/platform/refs/equipments/{id}/status', 'platform', 'ad.refs.disable', [
        'name' => 'Change equipment status',
        'name_ar' => 'تعطيل/تفعيل تجهيز',
        'b' => ['status' => 'disabled', 'reason' => 'لم يعد يُستهدف'],
        'r' => ['affected' => ['retailers' => 8]],
        'crit' => true,
    ]),
    ep('EP-AD-043F', 'SP-03', 'PATCH', '/platform/refs/currencies/{id}/status', 'platform', 'ad.refs.currency', [
        'name' => 'Change currency status',
        'name_ar' => 'تعطيل/تفعيل عملة',
        'b' => ['status' => 'disabled', 'reason' => 'عملة لم تعد تُسعَّر'],
        'r' => ['id' => 2, 'status' => 'disabled'],
        'crit' => true,
    ]),
    ep('EP-AD-043G', 'SP-03', 'GET', '/platform/refs/fx-rates', 'platform', 'ad.refs.currency', [
        'name' => 'List FX rates',
        'name_ar' => 'أسعار الصرف',
        'q' => listQuery(['filter[currency_id]' => '2']),
        'r' => [[
            'id' => 88,
            'currency_id' => 2,
            'rate' => 1500000,
            'effective_from' => '2026-03-01T00:00:00+03:00',
            'source' => 'manual',
            'entered_by' => 1,
        ]],
        'd' => 'DOC-07 §4.3.2. BR-AD-19: التغيير لا يعيد تسعير طلب قائم.',
    ]),

    ep('EP-AD-060', 'SP-04', 'GET', '/platform/channel-applications', 'platform', 'ad.channels.view', [
        'name' => 'List channel join applications',
        'name_ar' => 'طلبات انضمام القنوات',
        'q' => listQuery(['filter[status]' => 'under_review']),
        'r' => [[
            'id' => 21,
            'name' => 'شركة بردى',
            'legal_form' => 'llc',
            'cr_number' => 'C77881',
            'status' => 'under_review',
            'submitted_at' => '2026-02-28T11:00:00+03:00',
        ]],
        'd' => 'DOC-07 §4.2.2 الشكل 4. الحالات: under_review → provisioning | rejected.',
    ]),
    ep('EP-AD-061', 'SP-04', 'POST', '/platform/channel-applications/{id}/decide', 'platform', 'ad.channels.create', [
        'name' => 'Decide channel application',
        'name_ar' => 'بتّ طلب انضمام قناة',
        'b' => [
            'decision' => 'approve',
            'reason' => 'مستندات السجل التجاري مكتملة',
            'plan_id' => 2,
            'trial_days' => 14,
        ],
        'r' => ['application_id' => 21, 'channel_id' => 11, 'status' => 'provisioning'],
        'e' => [409 => 'illegal_transition'],
        'd' => 'decision: approve|reject. الموافقة تنشئ القناة بحالة قيد التهيئة (REQ-AD-020).',
        'crit' => true,
    ]),
    ep('EP-AD-062', 'SP-04', 'PUT', '/platform/channels/{id}', 'platform', 'ad.channels.update', [
        'name' => 'Update channel profile',
        'name_ar' => 'تعديل بيانات القناة',
        'b' => [
            'name' => 'شركة النور للتوزيع',
            'legal_form' => 'llc',
            'cr_number' => 'C12345',
            'activity_type_ids' => [3, 4],
            'internal_note' => 'تحديث السجل',
            'reason' => 'تصحيح الاسم التجاري',
        ],
        'r' => ['id' => 1],
        'd' => 'DOC-07 §4.2.7 تبويب نظرة عامة. BR-AD-11: سبب مكتوب إلزامي.',
    ]),
    ep('EP-AD-063', 'SP-04', 'GET', '/platform/channels/{id}/users', 'platform', 'ad.channels.view', [
        'name' => 'Channel users and roles',
        'name_ar' => 'مستخدمو القناة وأدوارهم',
        'q' => listQuery(),
        'r' => [[
            'id' => 10,
            'name' => 'محمد علي',
            'phone' => '+963944000000',
            'role' => 'channel_manager',
            'status' => 'active',
            'last_login_at' => '2026-03-01T08:10:00+03:00',
        ]],
        'd' => 'DOC-07 §4.2.7 تبويب المستخدمون والأدوار.',
    ]),
    ep('EP-AD-064', 'SP-04', 'POST', '/platform/channels/{id}/manager/reset', 'platform', 'ad.channels.update', [
        'name' => 'Reset channel manager account',
        'name_ar' => 'إعادة تعيين حساب مدير القناة',
        'b' => [
            'reason' => 'فقد الهاتف — تذكرة SUP-880',
            'invite_via' => 'whatsapp',
        ],
        'r' => ['invite_id' => 44, 'expires_at' => '2026-03-04T09:12:44+03:00'],
        'd' => 'رابط الدعوة صالح 72 ساعة ويُستهلك مرة واحدة.',
        'crit' => true,
    ]),
    ep('EP-AD-065A', 'SP-04', 'GET', '/platform/channels/{id}/coverage', 'platform', 'ad.channels.view', [
        'name' => 'Channel coverage',
        'name_ar' => 'المناطق والتغطية',
        'r' => [
            'zones' => [['id' => 12, 'name' => 'المزة', 'has_rep' => true]],
            'overlaps' => [['zone_id' => 12, 'other_channel_ids' => [9], 'exclusive' => false]],
            'zones_without_rep' => [13],
        ],
        'd' => 'DOC-07 §4.2.7 تبويب المناطق والتغطية. تحذير التداخل الحصري.',
    ]),
    ep('EP-AD-065B', 'SP-04', 'PUT', '/platform/channels/{id}/coverage', 'platform', 'ad.channels.update', [
        'name' => 'Update channel coverage',
        'name_ar' => 'تحديث تغطية القناة',
        'b' => [
            'governorate_ids' => [1],
            'zone_ids' => [12, 13],
            'reason' => 'توسيع التغطية إلى كفرسوسة',
        ],
        'r' => ['zone_ids' => [12, 13], 'overlap_warnings' => []],
        'd' => 'BR-AD-11: سبب مكتوب. لا يمسّ التسعير داخل القناة.',
    ]),
    ep('EP-AD-066', 'SP-04', 'GET', '/platform/channels/{id}/warehouses', 'platform', 'ad.channels.view', [
        'name' => 'Channel warehouses',
        'name_ar' => 'مستودعات القناة',
        'r' => [[
            'id' => 3,
            'name' => 'مستودع المزة',
            'status' => 'active',
            'lat' => 33.5,
            'lng' => 36.27,
            'served_zone_ids' => [12, 13],
        ]],
        'd' => 'DOC-07 §4.2.7 تبويب المستودعات — قراءة فقط من لوحة المنصة.',
    ]),
    ep('EP-AD-067', 'SP-04', 'GET', '/platform/channels/{id}/features', 'platform', 'ad.features.view', [
        'name' => 'Channel feature flags',
        'name_ar' => 'ميزات هذه القناة',
        'r' => [[
            'key' => 'offline_orders',
            'source' => 'plan',
            'enabled' => true,
            'overridden' => false,
        ]],
        'd' => 'DOC-07 §4.2.7 تبويب الميزات. الأسبقية: تجاوز يدوي ← الباقة ← الإعداد العالمي.',
    ]),
    ep('EP-AD-068', 'SP-04', 'POST', '/platform/channels/notify-managers', 'platform', 'ad.notify.send', [
        'name' => 'Notify channel managers (bulk)',
        'name_ar' => 'إشعار مديري القنوات',
        'b' => [
            'channel_ids' => [1, 2, 9],
            'title' => 'تحديث حدود الباقة',
            'body' => 'تم رفع حد المندوبين مؤقتاً لموسم رمضان',
            'channels' => ['in_app', 'whatsapp'],
        ],
        'r' => ['queued' => 3],
        'd' => 'DOC-07 §4.2.1 عمليات جماعية. حتى 50 قناة.',
    ]),

    ep('EP-AD-096', 'SP-16', 'GET', '/platform/dashboard/charts/{key}', 'platform', 'ad.dashboard.view', [
        'name' => 'Dashboard chart',
        'name_ar' => 'رسم لوحة القيادة',
        'q' => ['range' => '30d'],
        'r' => [
            'key' => 'daily_gmv',
            'points' => [['day' => '2026-02-28', 'value' => 420000000, 'previous' => 390000000]],
        ],
        'd' => 'DOC-07 §4.1.3. key ∈ daily_gmv | orders_by_governorate | top_channels | top_zones | adoption | heatmap. من اللقطة لا الحيّ (REQ-AD-010).',
        'e' => [404 => 'not_found'],
    ]),

    ep('EP-AD-100C', 'SP-17', 'GET', '/platform/plans/{id}', 'platform', 'ad.billing.plans', [
        'name' => 'Plan detail',
        'name_ar' => 'تفاصيل الباقة',
        'r' => [
            'id' => 2,
            'name' => 'نمو',
            'key' => 'growth',
            'price_monthly' => 25000000,
            'price_yearly' => 250000000,
            'limits' => ['users' => 25, 'warehouses' => 2, 'reps' => 20, 'skus' => 5000, 'storage_mb' => 2048, 'otp_monthly' => 20000],
            'features' => ['loyalty', 'multi_warehouse'],
            'on_exceed' => 'block',
            'is_public' => true,
            'status' => 'active',
        ],
        'd' => 'DOC-07 §4.5.1.',
    ]),
    ep('EP-AD-100D', 'SP-17', 'PUT', '/platform/plans/{id}', 'platform', 'ad.billing.plans', [
        'name' => 'Update plan',
        'name_ar' => 'تعديل باقة',
        'b' => [
            'name' => 'نمو',
            'price_monthly' => 28000000,
            'price_yearly' => 280000000,
            'limits' => ['users' => 30, 'warehouses' => 2, 'reps' => 25, 'skus' => 6000, 'storage_mb' => 2048, 'otp_monthly' => 25000],
            'features' => ['loyalty', 'multi_warehouse'],
            'on_exceed' => 'block',
            'is_public' => true,
            'status' => 'active',
            'reason' => 'تعديل سعر بعد مراجعة الإيراد',
        ],
        'r' => ['id' => 2],
        'd' => 'لا يغيّر اشتراكات قائمة إلا عند التجديد ما لم يُطبَّق مسار bulk-plan.',
    ]),

    ep('EP-AD-085A', 'SP-14', 'GET', '/platform/notifications/campaigns', 'platform', 'ad.notify.view', [
        'name' => 'Notification campaigns',
        'name_ar' => 'حملات الإشعارات',
        'q' => listQuery(['filter[status]' => 'scheduled']),
        'r' => [[
            'id' => 502,
            'title' => 'تحديث شروط الاستخدام',
            'status' => 'queued',
            'scheduled_at' => null,
            'estimated_recipients' => 12400,
        ]],
        'd' => 'DOC-07 §4.8.',
    ]),
    ep('EP-AD-085B', 'SP-14', 'GET', '/platform/notifications/campaigns/{id}', 'platform', 'ad.notify.view', [
        'name' => 'Campaign detail',
        'name_ar' => 'تفاصيل حملة',
        'r' => [
            'id' => 502,
            'title' => 'تحديث شروط الاستخدام',
            'status' => 'sent',
            'stats' => ['sent' => 12400, 'delivered' => 12110, 'read' => 6400, 'failed' => 90],
        ],
    ]),

    ep('EP-AD-139A', 'SP-17', 'GET', '/platform/settings/backup', 'platform', 'ad.settings.view', [
        'name' => 'Backup policy',
        'name_ar' => 'سياسة النسخ الاحتياطي',
        'r' => [
            'schedule' => '0 3 * * *',
            'destination' => 's3://b2b-backups',
            'retention_days' => 30,
            'encrypted' => true,
            'last_restore_test_at' => '2026-02-23T04:00:00+03:00',
            'last_restore_test_status' => 'ok',
        ],
        'd' => 'DOC-07 §4.12 تبويب النسخ الاحتياطي. NFR-AD-09.',
    ]),
    ep('EP-AD-139B', 'SP-17', 'PUT', '/platform/settings/backup', 'platform', 'ad.settings.update', [
        'name' => 'Update backup policy',
        'name_ar' => 'تحديث سياسة النسخ',
        'b' => [
            'schedule' => '0 3 * * *',
            'destination' => 's3://b2b-backups',
            'retention_days' => 30,
            'encrypted' => true,
            'password_confirmation' => '********',
            'reason' => 'تمديد الاحتفاظ إلى 30 يوماً',
        ],
        'r' => ['updated' => true],
        'crit' => true,
    ]),
    ep('EP-AD-139C', 'SP-17', 'POST', '/platform/system/backups', 'platform', 'ad.system.backup', [
        'name' => 'Trigger backup',
        'name_ar' => 'تشغيل نسخة احتياطية',
        'b' => ['reason' => 'قبل ترقية المخطط'],
        'r' => ['job_id' => 'job_bak_19'],
        'd' => 'DOC-07 §4.9 / NFR-AD-09.',
        'crit' => true,
    ]),
    ep('EP-AD-139D', 'SP-17', 'POST', '/platform/system/backups/restore-test', 'platform', 'ad.system.backup', [
        'name' => 'Run restore test',
        'name_ar' => 'اختبار الاستعادة',
        'b' => ['backup_id' => 'bak_2026-03-01'],
        'r' => ['job_id' => 'job_restore_test_4', 'status' => 'queued'],
        'd' => 'اختبار استعادة دوري. لا يمسّ بيئة الإنتاج.',
        'crit' => true,
    ]),

    ep('EP-AD-159A', 'SP-01', 'GET', '/platform/me', 'platform', null, [
        'name' => 'My platform profile',
        'name_ar' => 'ملفي الشخصي',
        'r' => [
            'id' => 1,
            'name' => 'منصّة',
            'email' => 'admin@platform.sy',
            'phone' => '+963991000000',
            'two_factor_enabled' => true,
            'roles' => ['platform_admin'],
        ],
        'd' => 'DOC-07 §4.12 ملفي الشخصي. متاح لكل أدوار المنصة.',
    ]),
    ep('EP-AD-159B', 'SP-01', 'PUT', '/platform/me', 'platform', null, [
        'name' => 'Update my profile',
        'name_ar' => 'تحديث ملفي',
        'b' => ['name' => 'منصّة', 'phone' => '+963991000000'],
        'r' => ['updated' => true],
    ]),
    ep('EP-AD-159C', 'SP-01', 'PUT', '/platform/me/password', 'platform', null, [
        'name' => 'Change my password',
        'name_ar' => 'تغيير كلمة المرور',
        'b' => [
            'current_password' => '********',
            'password' => '********',
            'password_confirmation' => '********',
        ],
        'r' => ['updated' => true],
        'e' => [422 => 'validation_failed'],
        'crit' => true,
    ]),
    ep('EP-AD-159D', 'SP-01', 'POST', '/platform/me/2fa/enable', 'platform', null, [
        'name' => 'Start 2FA setup',
        'name_ar' => 'بدء تفعيل التحقق بخطوتين',
        'b' => new stdClass(),
        'r' => ['secret' => 'otpauth://totp/...', 'qr_svg' => '<svg/>'],
        'd' => 'BR-AD-03: إلزامي لمدير المنصة ولمن يملك انتحال الجلسة.',
    ]),
    ep('EP-AD-159E', 'SP-01', 'POST', '/platform/me/2fa/confirm', 'platform', null, [
        'name' => 'Confirm 2FA setup',
        'name_ar' => 'تأكيد التحقق بخطوتين',
        'b' => ['code' => '123456'],
        'r' => ['enabled' => true, 'recovery_codes' => ['a1b2c3d4', 'e5f6g7h8']],
        'crit' => true,
    ]),
    ep('EP-AD-159F', 'SP-01', 'GET', '/platform/me/2fa/recovery-codes', 'platform', null, [
        'name' => '2FA recovery codes',
        'name_ar' => 'رموز الاسترداد',
        'r' => ['codes_remaining' => 8],
        'd' => 'الرموز نفسها لا تُعاد قراءتها بعد الإنشاء (BR-AD-21).',
    ]),
    ep('EP-AD-159G', 'SP-01', 'GET', '/platform/me/api-tokens', 'platform', null, [
        'name' => 'My API tokens',
        'name_ar' => 'رموز API',
        'r' => [['id' => 3, 'name' => 'ci', 'last_used_at' => null, 'created_at' => '2026-02-01T00:00:00+03:00']],
    ]),
    ep('EP-AD-159H', 'SP-01', 'POST', '/platform/me/api-tokens', 'platform', null, [
        'name' => 'Create API token',
        'name_ar' => 'إنشاء رمز API',
        'b' => [
            'name' => 'ci',
            'password_confirmation' => '********',
        ],
        'r' => ['id' => 4, 'token' => '2|shown_once'],
        'd' => 'BR-AD-04: تأكيد كلمة المرور. الرمز يُعرض مرة واحدة.',
        'crit' => true,
    ]),
    ep('EP-AD-159I', 'SP-01', 'DELETE', '/platform/me/api-tokens/{id}', 'platform', null, [
        'name' => 'Revoke API token',
        'name_ar' => 'إبطال رمز API',
        'r' => ['success' => true],
        'crit' => true,
    ]),

    ep('EP-AD-160A', 'SP-17', 'PUT', '/platform/team/{id}', 'platform', 'ad.team.update', [
        'name' => 'Update platform member',
        'name_ar' => 'تعديل عضو المنصة',
        'b' => [
            'name' => 'سارة الدعم',
            'role_ids' => [5],
            'reason' => 'تثبيت دور الدعم بعد انتهاء التجربة',
        ],
        'r' => ['id' => 4],
        'e' => [409 => 'illegal_transition'],
        'd' => 'BR-AD-05: لا يسحب دوره الأخير من نفسه. BR-AD-06: آخر مدير منصة لا يُعطَّل.',
        'crit' => true,
    ]),
    ep('EP-AD-160B', 'SP-17', 'DELETE', '/platform/team/{id}', 'platform', 'ad.team.delete', [
        'name' => 'Remove platform member',
        'name_ar' => 'حذف عضو المنصة',
        'b' => [
            'reason' => 'ترك العمل نهائياً',
            'password_confirmation' => '********',
        ],
        'r' => ['status' => 'removed'],
        'e' => [409 => 'illegal_transition'],
        'd' => 'AC-AD-15 / BR-AD-06: آخر مدير منصة نشط لا يُحذف.',
        'crit' => true,
        'dual' => true,
    ]),
];
